// apps/site/src/demos/project-picker/Demo.tsx
import { useMemo, useState } from 'react';
import type { EntityRef } from 'sg-widgets-core';
import { ProjectPicker } from '@/registry/sg/components/project-picker';
import { createDemoContext } from '../_shared/client';

const group = 'flex flex-col gap-2';
const label = 'text-muted-foreground text-xs font-medium tracking-wide uppercase';
// One control per row, full width of the pane, its caption on the line above.
const field = 'flex w-full flex-col gap-2';
const stack = 'flex flex-col gap-4';
const caption = 'text-muted-foreground text-xs';

const SIZES = [
  { size: 'sm', caption: 'Small' },
  { size: 'md', caption: 'Medium, the default' },
  { size: 'lg', caption: 'Large' },
] as const;

export default function ProjectPickerDemo() {
  const context = useMemo(() => createDemoContext(), []);
  // The name is the mock's. A live project arrives bare and the picker resolves it.
  const preset: EntityRef = context.live
    ? { type: 'Project', id: context.projectId }
    : { type: 'Project', id: context.projectId, name: 'Blue Moon Rising' };

  const [one, setOne] = useState<EntityRef | null>(null);
  const [archived, setArchived] = useState<EntityRef | null>(null);
  // A bare reference: type and id, no name. Resolved on mount.
  const [bare, setBare] = useState<EntityRef | null>({ type: 'Project', id: context.projectFor(71) });

  return (
    <div className="flex flex-col gap-3">
      <section className={group} data-demo-case="single">
        <h4 className={label}>One project</h4>
        <div className={field}>
          <span className={caption}>One project, clearable</span>
          <ProjectPicker context={context} value={one} onValueChange={setOne} clearable />
        </div>
      </section>

      <section className={group} data-demo-case="archived">
        <h4 className={label}>Archived projects included</h4>
        <div className={field}>
          <span className={caption}>Archived projects included</span>
          <ProjectPicker context={context} includeArchived value={archived} onValueChange={setArchived} />
        </div>
      </section>

      <section className={group} data-demo-case="hydrate">
        <h4 className={label}>Bare reference, resolved on mount</h4>
        <div className={field}>
          <span className={caption}>Type and id in, name resolved on mount</span>
          <ProjectPicker context={context} value={bare} onValueChange={setBare} clearable />
        </div>
      </section>

      <section className={group} data-demo-case="states">
        <h4 className={label}>Sizes, then disabled, read-only, invalid</h4>
        <div className={stack}>
          {SIZES.map(({ size, caption: sizeCaption }) => (
            <div className={field} key={size}>
              <span className={caption}>{sizeCaption}</span>
              <ProjectPicker context={context} value={preset} size={size} />
            </div>
          ))}
          <div className={field}>
            <span className={caption}>Disabled</span>
            <ProjectPicker context={context} value={preset} disabled />
          </div>
          <div className={field}>
            <span className={caption}>Read-only</span>
            <ProjectPicker context={context} value={preset} readonly />
          </div>
          <div className={field}>
            <span className={caption}>Invalid</span>
            <ProjectPicker context={context} value={preset} invalid />
          </div>
        </div>
      </section>
    </div>
  );
}

// apps/site/src/demos/status-picker/Demo.svelte
<script lang="ts">
	import StatusPicker from '$lib/registry/components/status-picker.svelte';
	import { createDemoContext } from '../_shared/client';
	import { setDemoClient } from '../_shared/svelte';

	// Live mode has one project, the toolbar's; the mock has 70 and 71.
	const context = createDemoContext();
	const client = setDemoClient(context.client);
	const projectId = context.projectId;
	const otherProjectId = context.projectFor(71);

	let inProjectA = $state<string | undefined>('ip');
	let inProjectB = $state<string | undefined>('pndad');
	let shared = $state<string | undefined>(undefined);
	let project = $state<string | undefined>('Active');
	let unknown = $state<string | undefined>('zz_retired');
	let switching = $state<string | undefined>('part');
	let switchTo = $state(otherProjectId);

	const group = 'flex flex-col gap-2';
	const label = 'text-muted-foreground text-xs font-medium tracking-wide uppercase';
	const row = 'flex flex-wrap items-start gap-3';
	const box = 'w-64';
	const readout = 'text-muted-foreground font-mono text-xs tabular-nums';
</script>

<div class="flex flex-col gap-4">
	<section class={group}>
		<h4 class={label}>
			{projectId === otherProjectId
				? `Version, in project ${projectId}`
				: `Version, in project ${projectId} and in project ${otherProjectId}`}
		</h4>
		<div class={row}>
			<div class={box} data-demo="p70">
				<StatusPicker {client} entityType="Version" {projectId} bind:value={inProjectA} />
			</div>
			<div class={box} data-demo="p71">
				<StatusPicker {client} entityType="Version" projectId={otherProjectId} bind:value={inProjectB} />
			</div>
		</div>
	</section>

	<section class={group}>
		<h4 class={label}>The statuses both projects offer</h4>
		<div class={row}>
			<div class={box} data-demo="both">
				<StatusPicker {client} entityType="Version" projectIds={[projectId, otherProjectId]} bind:value={shared} />
			</div>
			<span class={readout}>{shared ?? '—'}</span>
		</div>
	</section>

	<section class={group}>
		<h4 class={label}>Project, whose status field is a plain list with no icons</h4>
		<div class={row}>
			<div class={box} data-demo="project">
				<StatusPicker {client} entityType="Project" bind:value={project} />
			</div>
		</div>
	</section>

	<section class={group}>
		<h4 class={label}>A code the field does not carry, and the code instead of the label</h4>
		<div class={row}>
			<div class={box} data-demo="unknown">
				<StatusPicker {client} entityType="Version" {projectId} bind:value={unknown} />
			</div>
			<div class={box}>
				<StatusPicker
					{client}
					entityType="Version"
					{projectId}
					value="ip"
					showCode
					clearable={false}
				/>
			</div>
		</div>
	</section>

	<section class={group} data-demo="switch">
		<h4 class={label}>Switching project drops a status the new one hides</h4>
		<div class={row}>
			<div class={box} data-demo="switching">
				<StatusPicker {client} entityType="Version" projectId={switchTo} bind:value={switching} />
			</div>
			<button
				type="button"
				class="border-border hover:bg-accent hover:text-accent-foreground h-9 rounded-md border px-2 text-sm transition-colors duration-150 ease-out"
				onclick={() => (switchTo = switchTo === projectId ? otherProjectId : projectId)}
			>
				Project {switchTo}
			</button>
			<span class={readout}>{switching ?? '—'}</span>
		</div>
	</section>

	<section class={group}>
		<h4 class={label}>Disabled, read-only, invalid</h4>
		<div class={row}>
			<div class={box}>
				<StatusPicker {client} entityType="Version" {projectId} value="apr" disabled />
			</div>
			<div class={box}>
				<StatusPicker {client} entityType="Version" {projectId} value="apr" readonly />
			</div>
			<div class={box}>
				<StatusPicker {client} entityType="Version" {projectId} value="apr" invalid />
			</div>
		</div>
	</section>

	<section class={group}>
		<h4 class={label}>Sizes</h4>
		<div class={row}>
			<div class={box}>
				<StatusPicker {client} entityType="Version" {projectId} value="rev" size="sm" />
			</div>
			<div class={box}>
				<StatusPicker {client} entityType="Version" {projectId} value="rev" size="md" />
			</div>
			<div class={box}>
				<StatusPicker {client} entityType="Version" {projectId} value="rev" size="lg" />
			</div>
		</div>
	</section>
</div>
