// packages/react/src/registry/sg/components/filter-bar.tsx
import { useEffect, useState, type ReactNode } from 'react';
import type {
  FacetValue,
  FieldSchema,
  FilterCondition,
  FilterGroup,
  Operator,
  Scalar,
  SgContext,
  StatusRecord,
  WireGroup,
} from '@sg-widgets/core';
import {
  conditionArity,
  conditionParts,
  conditionValues,
  describeCondition,
  emptyFilter,
  facetValues,
  findCondition,
  renderKindFor,
  setFacet,
  toApi3Hash,
  asFilterGroup,
  group,
  matchesTokens,
  withoutPaths,
} from '@sg-widgets/core';
import { PlusIcon, SearchX, TriangleAlert, XIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Command, CommandEmpty, CommandInput, CommandItem, CommandList } from '@/components/ui/command';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { cn } from '@/lib/utils';
import {
  CONTROL_BUTTON,
  CONTROL_GLYPH,
  CONTROL_HEIGHT,
  CONTROL_PAD,
  type ControlSize,
} from '@/registry/sg/components/control-classes';
import { useEntityFields } from '@/registry/sg/components/entity-fields';
import { FilterDialog } from '@/registry/sg/components/filter-dialog';
import { CHIP_CROSS, REMOVE_CONTROL, type ChipSize } from '@/registry/sg/components/leaf-classes';
import { StateLine } from '@/registry/sg/components/state-line';
import { StatusBadge, type StatusBadgeSize } from '@/registry/sg/components/status-badge';

export type FilterBarSize = ControlSize;

/** A cross inside the pill sits one step under it on the chip ladder. */
const CROSS: Record<FilterBarSize, ChipSize> = { sm: 'xs', md: 'sm', lg: 'md' };
/**
 * The pill's trailing edge: the room above the cross, so its box sits as far from the
 * right as from the top (`docs/design-rules.md` rule 3).
 */
const CROSS_PAD: Record<FilterBarSize, string> = { sm: 'pr-[7px]', md: 'pr-2', lg: 'pr-[9px]' };
/** A badge sits one step under the pill it is in (`docs/design-rules.md` rule 3). */
const BADGE: Record<FilterBarSize, StatusBadgeSize> = { sm: 'xs', md: 'sm', lg: 'md' };
/**
 * What a pill's value may take before it truncates. A facet with everything ticked would
 * otherwise run the bar past the width it was given (`docs/design-rules.md` rule 2).
 */
const VALUE_WIDTH = 'max-w-64';

export interface FilterBarProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange'> {
  /** The root element. */
  ref?: React.Ref<HTMLDivElement>;

  entityType: string;
  /** The widget context. Every read goes through it, so widgets on a page share one cache. */
  context: SgContext;
  /** Field names to offer as pills, in order. */
  facets: string[];
  /** A name per facet, for a field whose schema label is not what the page calls it. */
  labels?: Record<string, string>;
  /** Values a pill names before the rest reads as `+n`. `0` names every one. */
  maxValues?: number;
  value: FilterGroup;
  hidePaths?: string[];
  size?: FilterBarSize;
  disabled?: boolean;
  /**
   * Counts per value for one facet. Wire it to a `_summarize` grouping call.
   * Without it the bar reads one page of rows and tallies them.
   */
  /** Conditions every facet query carries, such as a project scope. Never edited by the bar. */
  baseFilter?: FilterGroup | WireGroup | null;
  counts?: (field: string, filters: WireGroup | null) => Promise<Record<string, number>>;
  /** Rows read for the tally when `counts` is not given. */
  sampleSize?: number;
  onChange?: (value: FilterGroup) => void;
  className?: string;
}

/**
 * Quick facets over one entity type.
 *
 * An untouched facet is a quiet pill naming its field; ticking a value turns it into
 * a pill reading the field and the values ticked, and opening it again reopens the
 * checklist. The pill adds its condition to the bound tree, and More filters opens
 * the same tree in the full editor, so the two edit one value: a condition the editor
 * wrote on an operator the checklist cannot hold reads as text in its pill.
 *
 * Counts come from a `_summarize` grouping call when one is wired to `counts`, and
 * otherwise from tallying one page of rows, which makes them as complete as the page
 * size allowed.
 */
export function FilterBar({
  entityType,
  context,
  facets,
  labels = {},
  value = emptyFilter(),
  hidePaths = [],
  size = 'md',
  maxValues = 2,
  disabled = false,
  counts,
  baseFilter = null,
  sampleSize = 200,
  onChange,
  className,
  ref,
  ...rest
}: FilterBarProps) {
  const fields = useEntityFields(context, entityType);
  const [tally, setTally] = useState<Record<string, FacetValue[]>>({});
  /** The `Status` rows, for a facet over a status field (probe 010). */
  const [statuses, setStatuses] = useState<Record<string, StatusRecord>>({});
  /** What the open facet's search box holds. */
  const [facetQuery, setFacetQuery] = useState('');
  const [counting, setCounting] = useState(true);
  /** What a failed tally said, shown in place of the values. */
  const [failure, setFailure] = useState<string | null>(null);

  // Counts are read against the filter with every facet's own condition stripped, so
  // ticking one value does not empty its neighbours. One read serves every pill.
  const base = asFilterGroup(baseFilter);
  const scope = JSON.stringify(toApi3Hash(base ? group('and', [base, withoutPaths(value, facets)]) : withoutPaths(value, facets)));

  useEffect(() => {
    const present = facets.map((name) => fields[name]).filter((f): f is FieldSchema => Boolean(f));
    if (present.length === 0) return;
    let live = true;
    setCounting(true);
    setFailure(null);
    const filters = JSON.parse(scope) as WireGroup | null;
    const load = async (): Promise<Record<string, FacetValue[]>> => {
      const out: Record<string, FacetValue[]> = {};
      if (counts) {
        for (const field of present) {
          const found = await counts(field.name, filters);
          out[field.name] = facetValues([], field).map((v) => ({ ...v, count: found[v.key] ?? 0 }));
        }
        return out;
      }
      const rows = await context.client.search(entityType, {
        filters,
        fields: present.map((f) => f.name),
        page: { size: sampleSize },
      });
      for (const field of present) out[field.name] = facetValues(rows.data, field);
      return out;
    };
    void load()
      .then((found) => {
        if (live) setTally(found);
      })
      .catch((error: unknown) => {
        if (live) setFailure(error instanceof Error ? error.message : String(error));
      })
      .finally(() => {
        if (live) setCounting(false);
      });
    return () => {
      live = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [context.client, entityType, fields, facets.join(','), scope, sampleSize, counts]);

  useEffect(() => {
    let live = true;
    void context.statuses
      .byCode()
      .then((table) => {
        if (live) setStatuses(Object.fromEntries(table));
      })
      .catch(() => {
        // A facet without the table still reads: a badge falls back to its own code.
      });
    return () => {
      live = false;
    };
  }, [context.statuses]);

  /** The name a pill and its popover carry: the caller's, else the schema's, else the path. */
  const labelOf = (name: string): string => labels[name] ?? fields[name]?.displayName ?? name;
  /** True where the facet's values are status codes, which draw as badges rather than text. */
  const isStatus = (name: string): boolean => renderKindFor(fields[name]?.dataType ?? '') === 'status';

  /** One facet value, as a badge on a status field and as its label everywhere else. */
  const valueLabel = (name: string, key: string, label: string): ReactNode =>
    isStatus(name) ? (
      <StatusBadge
        code={key}
        status={statuses[key] ?? null}
        field={fields[name] ?? null}
        size={BADGE[size]}
        siteUrl={context.siteUrl}
      />
    ) : (
      label
    );

  /**
   * A pill's value: the values it has room to name, then `+n`. It is capped and
   * truncated with the whole list in its `title`, so a facet with everything ticked
   * never stretches the bar.
   */
  const pillValues = (name: string, shown: ReturnType<typeof conditionValues> | null): ReactNode => {
    if (!shown || shown.shown.length === 0) return null;
    return (
      <span
        data-slot="filter-pill-values"
        className={cn('flex min-w-0 items-center gap-1.5 truncate', VALUE_WIDTH)}
        title={shown.title}
      >
        {shown.values.length > 0
          ? shown.shown.map((label, i) => (
              <span key={keyOf(shown.values[i] as Scalar)} className="flex min-w-0 items-center truncate">
                {valueLabel(name, keyOf(shown.values[i] as Scalar), label)}
              </span>
            ))
          : shown.shown.map((label) => (
              <span key={label} className="min-w-0 truncate">
                {label}
              </span>
            ))}
        {shown.overflow > 0 ? (
          <span data-slot="filter-pill-overflow" className="text-muted-foreground shrink-0 tabular-nums">
            +{shown.overflow}
          </span>
        ) : null}
      </span>
    );
  };

  const conditionOf = (name: string): FilterCondition | null => findCondition(value, name)?.condition ?? null;

  const selectedOf = (name: string): Scalar[] => {
    const found = conditionOf(name);
    return found && Array.isArray(found.value) ? (found.value as Scalar[]) : [];
  };

  const keyOf = (v: Scalar): string => (v !== null && typeof v === 'object' ? `${v.type}:${v.id}` : String(v));

  /** The list operator the checklist writes: the one the pill already holds, else `in`. */
  const listOperator = (name: string): Operator => {
    const found = conditionOf(name);
    return found && Array.isArray(found.value) ? found.operator : 'in';
  };

  function toggle(name: string, option: FacetValue) {
    const selected = selectedOf(name);
    const next = selected.some((v) => keyOf(v) === option.key)
      ? selected.filter((v) => keyOf(v) !== option.key)
      : [...selected, option.value];
    onChange?.(setFacet(value, name, next, listOperator(name)));
  }

  const facetList = (name: string): ReactNode => {
    const selected = selectedOf(name);
    // The box matches what it was given rather than what a read answered, so the rows
    // drawn are the rows the list holds.
    const shown = (tally[name] ?? []).filter((option) => matchesTokens(facetQuery, option.label, option.key));
    return (
      <PopoverContent className="w-64 p-0" align="start">
        <Command
          shouldFilter={false}
          items={shown.map((option) => option.key)}
          query={facetQuery}
          onQueryChange={setFacetQuery}
        >
          <CommandInput placeholder="Search values…" />
          <CommandList>
            {counting ? (
              <p className="text-muted-foreground py-6 text-center text-sm">Counting…</p>
            ) : failure ? (
              <StateLine state="error" slotName="filter-bar-error" icon={TriangleAlert} label={failure} />
            ) : (
              <>
                <CommandEmpty>
                  <StateLine state="empty" icon={SearchX} label="No value." pad="none" />
                </CommandEmpty>
                {shown.map((option) => (
                  <CommandItem
                    key={option.key}
                    value={option.key}
                    data-option={option.key}
                    onSelect={() => toggle(name, option)}
                  >
                    <Checkbox
                      checked={selected.some((v) => keyOf(v) === option.key)}
                      tabIndex={-1}
                      aria-hidden="true"
                    />
                    <span className="flex min-w-0 flex-1 items-center truncate" title={option.label}>
                      {valueLabel(name, option.key, option.label)}
                    </span>
                    <span className="text-muted-foreground text-xs tabular-nums" data-slot="facet-count">
                      {option.count}
                    </span>
                  </CommandItem>
                ))}
              </>
            )}
          </CommandList>
        </Command>
        {selected.length > 0 ? (
          <div className="border-border border-t p-1">
            <Button
              variant="ghost"
              size={CONTROL_BUTTON[size]}
              className="w-full"
              data-slot="filter-pill-clear"
              onClick={() => onChange?.(setFacet(value, name, []))}
            >
              Clear
            </Button>
          </div>
        ) : null}
      </PopoverContent>
    );
  };

  const activeCount = facets.filter((name) => Boolean(conditionOf(name))).length;

  return (
    <div
      ref={ref}
      data-slot="filter-bar"
      className={cn('flex w-full min-w-0 flex-wrap items-center gap-2', className)}
      {...rest}
    >
      {facets.map((name) => {
        const field = fields[name];
        const found = conditionOf(name);
        const parts = found ? conditionParts(found, field) : null;
        const shown = found ? conditionValues(found, field, maxValues) : null;
        const remove = (label: string) => (
          <button
            type="button"
            disabled={disabled}
            data-slot="filter-pill-remove"
            aria-label={`Remove ${label} filter`}
            className={cn(REMOVE_CONTROL, 'disabled:pointer-events-none disabled:opacity-50')}
            onClick={() => onChange?.(withoutPaths(value, [name]))}
          >
            <XIcon aria-hidden="true" className={CHIP_CROSS[CROSS[size]]} />
          </button>
        );
        if (!found || !parts || conditionArity(found, field?.dataType ?? '') === 'many') {
          // One popover and one trigger across both looks, so the first tick does not close the list.
          return (
            <Popover key={name}>
              <div
                data-slot="filter-pill"
                data-field={name}
                data-size={size}
                data-active={found ? 'true' : undefined}
                role={found ? 'group' : undefined}
                aria-label={found ? describeCondition(found, field) : undefined}
                className={cn(
                  'border-border inline-flex max-w-full min-w-0 items-center overflow-hidden rounded-lg border text-sm',
                  CONTROL_HEIGHT[size],
                  found && parts && CROSS_PAD[size],
                  found ? 'bg-background' : 'text-muted-foreground max-w-72 border-dashed',
                )}
              >
                <PopoverTrigger
                  disabled={disabled || !field}
                  data-slot="filter-pill-trigger"
                  className={cn(
                    'hover:bg-muted hover:text-foreground focus-visible:ring-ring/50 inline-flex min-w-0 items-center gap-1.5 outline-none focus-visible:ring-3 focus-visible:ring-inset disabled:pointer-events-none disabled:opacity-50',
                    CONTROL_HEIGHT[size],
                    CONTROL_PAD[size],
                  )}
                >
                  {!found || !parts ? (
                    <>
                      <PlusIcon className={cn('shrink-0', CONTROL_GLYPH[size])} />
                      <span className="min-w-0 truncate">{labelOf(name)}</span>
                    </>
                  ) : (
                    <>
                      <span data-slot="filter-pill-field" className="shrink-0 font-medium">
                        {labelOf(name)}
                      </span>
                      {found.operator !== 'in' ? <span className="text-muted-foreground shrink-0">{parts.operator}</span> : null}
                      {pillValues(name, shown)}
                    </>
                  )}
                </PopoverTrigger>
                {found && parts ? remove(labelOf(name)) : null}
              </div>
              {facetList(name)}
            </Popover>
          );
        }
        // A condition the editor wrote on an operator no checklist can hold reads as text.
        return (
          <div
            key={name}
            data-slot="filter-pill"
            data-field={name}
            data-size={size}
            data-active="true"
            role="group"
            aria-label={describeCondition(found, field)}
            className={cn(
              'border-border bg-background inline-flex max-w-full min-w-0 items-center overflow-hidden rounded-lg border text-sm',
              CONTROL_HEIGHT[size],
              CROSS_PAD[size],
            )}
          >
            <span
              className={cn('inline-flex min-w-0 items-center gap-1.5', CONTROL_HEIGHT[size], CONTROL_PAD[size])}
            >
              <span data-slot="filter-pill-field" className="shrink-0 font-medium">
                {labelOf(name)}
              </span>
              <span className="text-muted-foreground shrink-0">{parts.operator}</span>
              {pillValues(name, shown)}
            </span>
            {remove(labelOf(name))}
          </div>
        );
      })}

      {activeCount > 0 ? (
        <Button
          variant="ghost"
          size={CONTROL_BUTTON[size]}
          disabled={disabled}
          className="text-muted-foreground"
          data-slot="filter-clear-all"
          onClick={() => onChange?.(withoutPaths(value, facets))}
        >
          Clear all
        </Button>
      ) : null}

      <FilterDialog
        entityType={entityType}
        context={context}
        hidePaths={hidePaths}
        disabled={disabled}
        size={size}
        label="More filters"
        value={value}
        onChange={(next) => onChange?.(next)}
      />
    </div>
  );
}

// packages/svelte/src/lib/registry/components/filter-bar.svelte
<script lang="ts" module>
	import {
		CONTROL_BUTTON,
		CONTROL_GLYPH,
		CONTROL_HEIGHT,
		CONTROL_PAD,
		type ControlSize
	} from '$lib/registry/components/control-classes.js';
	import { CHIP_CROSS, type ChipSize } from '$lib/registry/components/leaf-classes.js';
	import type { StatusBadgeSize } from '$lib/registry/components/status-badge.svelte';

	export type FilterBarSize = ControlSize;

	/** A cross inside the pill sits one step under it on the chip ladder. */
	const CROSS: Record<FilterBarSize, ChipSize> = { sm: 'xs', md: 'sm', lg: 'md' };
	/**
	 * The pill's trailing edge: the room above the cross, so its box sits as far from the
	 * right as from the top (`docs/design-rules.md` rule 3).
	 */
	const CROSS_PAD: Record<FilterBarSize, string> = { sm: 'pr-[7px]', md: 'pr-2', lg: 'pr-[9px]' };
	/** A badge sits one step under the pill it is in (`docs/design-rules.md` rule 3). */
	const BADGE: Record<FilterBarSize, StatusBadgeSize> = { sm: 'xs', md: 'sm', lg: 'md' };
	/**
	 * What a pill's value may take before it truncates. A facet with everything ticked
	 * would otherwise run the bar past the width it was given (`docs/design-rules.md` rule 2).
	 */
	const VALUE_WIDTH = 'max-w-64';
</script>

<script lang="ts">
	import type { HTMLAttributes } from 'svelte/elements';
	import PlusIcon from '@lucide/svelte/icons/plus';
	import SearchXIcon from '@lucide/svelte/icons/search-x';
	import TriangleAlertIcon from '@lucide/svelte/icons/triangle-alert';
	import XIcon from '@lucide/svelte/icons/x';
	import type {
		FacetValue,
		FieldSchema,
		FilterCondition,
		FilterGroup,
		Operator,
		Scalar,
		SgContext,
		WireGroup
	} from '@sg-widgets/core';
	import {
		conditionArity,
		conditionParts,
		conditionValues,
		describeCondition,
		emptyFilter,
		facetValues,
		findCondition,
		renderKindFor,
		setFacet,
		toApi3Hash,
		asFilterGroup,
		group,
		matchesTokens,
		withoutPaths
	} from '@sg-widgets/core';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Checkbox } from '$lib/components/ui/checkbox/index.js';
	import * as Command from '$lib/components/ui/command/index.js';
	import * as Popover from '$lib/components/ui/popover/index.js';
	import { cn, type WithElementRef } from '$lib/utils.js';
	import { entityFields } from '$lib/registry/components/entity-fields.svelte.js';
	import FilterDialog from '$lib/registry/components/filter-dialog.svelte';
	import { REMOVE_CONTROL } from '$lib/registry/components/leaf-classes.js';
	import StateLine from '$lib/registry/components/state-line.svelte';
	import StatusBadge from '$lib/registry/components/status-badge.svelte';

	type Props = WithElementRef<HTMLAttributes<HTMLDivElement>, HTMLDivElement> & {
		entityType: string;
		/** The widget context. Every read goes through it, so widgets on a page share one cache. */
		context: SgContext;
		/** Field names to offer as pills, in order. */
		facets: string[];
		/** A name per facet, for a field whose schema label is not what the page calls it. */
		labels?: Record<string, string>;
		/** Values a pill names before the rest reads as `+n`. `0` names every one. */
		maxValues?: number;
		value: FilterGroup;
		hidePaths?: string[];
		size?: FilterBarSize;
		disabled?: boolean;
		/**
		 * Counts per value for one facet. Wire it to a `_summarize` grouping call.
		 * Without it the bar reads one page of rows and tallies them.
		 */
		/** Conditions every facet query carries, such as a project scope. Never edited by the bar. */
		baseFilter?: FilterGroup | WireGroup | null;
		counts?: (field: string, filters: WireGroup | null) => Promise<Record<string, number>>;
		/** Rows read for the tally when `counts` is not given. */
		sampleSize?: number;
		onChange?: (value: FilterGroup) => void;
		class?: string;
	};

	let {
		entityType,
		context,
		facets,
		labels = {},
		value = $bindable(emptyFilter()),
		hidePaths = [],
		size = 'md',
		maxValues = 2,
		disabled = false,
		counts,
		baseFilter = null,
		sampleSize = 200,
		onChange,
		class: className,
		ref = $bindable(null),
		...rest
	}: Props = $props();

	const schemaFields = entityFields(
		() => context,
		() => entityType
	);
	const fields = $derived(schemaFields.current);

	// Counts are read against the filter with every facet's own condition stripped, so
	// ticking one value does not empty its neighbours. One read serves every pill.
	const base = $derived(asFilterGroup(baseFilter));
	const scope = $derived(toApi3Hash(base ? group('and', [base, withoutPaths(value, facets)]) : withoutPaths(value, facets)));
	const tally = $derived(loadFacets(scope, fields, facets));
	/** What the open facet's search box holds. */
	let facetQuery = $state('');
	const activeCount = $derived(facets.filter((name) => Boolean(findCondition(value, name))).length);

	async function loadFacets(
		filters: WireGroup | null,
		schemaFields: Record<string, FieldSchema>,
		names: string[]
	): Promise<Record<string, FacetValue[]>> {
		const present = names.map((name) => schemaFields[name]).filter((f): f is FieldSchema => Boolean(f));
		if (present.length === 0) return {};
		if (counts) {
			const out: Record<string, FacetValue[]> = {};
			for (const field of present) {
				const found = await counts(field.name, filters);
				out[field.name] = facetValues([], field).map((v) => ({ ...v, count: found[v.key] ?? 0 }));
			}
			return out;
		}
		const rows = await context.client.search(entityType, {
			filters,
			fields: present.map((f) => f.name),
			page: { size: sampleSize }
		});
		const out: Record<string, FacetValue[]> = {};
		for (const field of present) out[field.name] = facetValues(rows.data, field);
		return out;
	}

	/** The `Status` rows, for a facet over a status field (probe 010). */
	// A facet without the table still reads: a badge falls back to its own code.
	const statuses = $derived(context.statuses.byCode());

	/** The name a pill and its popover carry: the caller's, else the schema's, else the path. */
	function labelOf(name: string): string {
		return labels[name] ?? fields[name]?.displayName ?? name;
	}

	/** True where the facet's values are status codes, which draw as badges rather than text. */
	function isStatus(name: string): boolean {
		return renderKindFor(fields[name]?.dataType ?? '') === 'status';
	}

	function conditionOf(name: string): FilterCondition | null {
		return findCondition(value, name)?.condition ?? null;
	}

	function selectedOf(name: string): Scalar[] {
		const found = conditionOf(name);
		return found && Array.isArray(found.value) ? (found.value as Scalar[]) : [];
	}

	function keyOf(v: Scalar): string {
		if (v !== null && typeof v === 'object') return `${v.type}:${v.id}`;
		return String(v);
	}

	function commit(next: FilterGroup): void {
		value = next;
		onChange?.(next);
	}

	/** The list operator the checklist writes: the one the pill already holds, else `in`. */
	function listOperator(name: string): Operator {
		const found = conditionOf(name);
		return found && Array.isArray(found.value) ? found.operator : 'in';
	}

	function toggle(name: string, option: FacetValue): void {
		const selected = selectedOf(name);
		const next = selected.some((v) => keyOf(v) === option.key)
			? selected.filter((v) => keyOf(v) !== option.key)
			: [...selected, option.value];
		commit(setFacet(value, name, next, listOperator(name)));
	}
</script>

{#snippet remove(name: string, label: string)}
	<button
		type="button"
		{disabled}
		data-slot="filter-pill-remove"
		aria-label="Remove {label} filter"
		class={cn(REMOVE_CONTROL, 'disabled:pointer-events-none disabled:opacity-50')}
		onclick={() => commit(withoutPaths(value, [name]))}
	>
		<XIcon aria-hidden="true" class={CHIP_CROSS[CROSS[size]]} />
	</button>
{/snippet}

{#snippet valueLabel(name: string, key: string, label: string)}
	{#if isStatus(name)}
		{#await statuses then table}
			<StatusBadge
				code={key}
				status={table.get(key) ?? null}
				field={fields[name] ?? null}
				size={BADGE[size]}
				siteUrl={context.siteUrl}
			/>
		{/await}
	{:else}
		{label}
	{/if}
{/snippet}

<!--
	A pill's value: the values it has room to name, then `+n`. It is capped and truncated
	with the whole list in its `title`, so a facet with everything ticked never stretches
	the bar.
-->
{#snippet pillValues(name: string, shown: ReturnType<typeof conditionValues>)}
	{#if shown.shown.length > 0}
		<span
			data-slot="filter-pill-values"
			class={cn('flex min-w-0 items-center gap-1.5 truncate', VALUE_WIDTH)}
			title={shown.title}
		>
			{#each shown.shown as label, i (i)}
				<span class="flex min-w-0 items-center truncate">
					{#if shown.values.length > 0}
						{@render valueLabel(name, keyOf(shown.values[i] as Scalar), label)}
					{:else}
						{label}
					{/if}
				</span>
			{/each}
			{#if shown.overflow > 0}
				<span data-slot="filter-pill-overflow" class="text-muted-foreground shrink-0 tabular-nums">
					+{shown.overflow}
				</span>
			{/if}
		</span>
	{/if}
{/snippet}

{#snippet facetList(name: string)}
	{@const selected = selectedOf(name)}
	<Popover.Content strategy="fixed" class="w-64 p-0" align="start">
		<Command.Root shouldFilter={false}>
			<Command.Input bind:value={facetQuery} placeholder="Search values…" />
			<Command.List>
				{#await tally}
					<p class="text-muted-foreground py-6 text-center text-sm">Counting…</p>
				{:then found}
					<Command.Empty>
						<StateLine state="empty" icon={SearchXIcon} label="No value." pad="none" />
					</Command.Empty>
					<!-- The box matches what it was given rather than what a read answered, so the rows drawn are the rows the list holds. -->
					{#each (found[name] ?? []).filter((option) => matchesTokens(facetQuery, option.label, option.key)) as option (option.key)}
						<Command.Item
							value={option.key}
							data-option={option.key}
							onSelect={() => toggle(name, option)}
						>
							<Checkbox
								checked={selected.some((v) => keyOf(v) === option.key)}
								tabindex={-1}
								aria-hidden="true"
							/>
							<span class="flex min-w-0 flex-1 items-center truncate" title={option.label}>
								{@render valueLabel(name, option.key, option.label)}
							</span>
							<span class="text-muted-foreground text-xs tabular-nums" data-slot="facet-count">
								{option.count}
							</span>
						</Command.Item>
					{/each}
				{:catch error}
					<StateLine
						state="error"
						slotName="filter-bar-error"
						icon={TriangleAlertIcon}
						label={error.message}
					/>
				{/await}
			</Command.List>
		</Command.Root>
		{#if selected.length > 0}
			<div class="border-border border-t p-1">
				<Button
					variant="ghost"
					size={CONTROL_BUTTON[size]}
					class="w-full"
					data-slot="filter-pill-clear"
					onclick={() => commit(setFacet(value, name, []))}
				>
					Clear
				</Button>
			</div>
		{/if}
	</Popover.Content>
{/snippet}

<!--
	Quick facets over one entity type.

	An untouched facet is a quiet pill naming its field; ticking a value turns it into
	a pill reading the field and the values ticked, and opening it again reopens the
	checklist. The pill adds its condition to the bound tree, and More filters opens
	the same tree in the full editor, so the two edit one value: a condition the editor
	wrote on an operator the checklist cannot hold reads as text in its pill.

	Counts come from a `_summarize` grouping call when one is wired to `counts`, and
	otherwise from tallying one page of rows, which makes them as complete as the page
	size allowed.
-->
<div
	bind:this={ref}
	data-slot="filter-bar"
	class={cn('flex w-full min-w-0 flex-wrap items-center gap-2', className)}
	{...rest}
>
	{#each facets as name (name)}
		{@const field = fields[name]}
		{@const found = conditionOf(name)}
		{@const parts = found ? conditionParts(found, field) : null}
		{@const shown = found ? conditionValues(found, field, maxValues) : null}
		{#if !found || conditionArity(found, field?.dataType ?? '') === 'many'}
			<!-- One popover and one trigger across both looks, so the first tick does not close the list. -->
			<Popover.Root>
				<div
					data-slot="filter-pill"
					data-field={name}
					data-size={size}
					data-active={found ? 'true' : undefined}
					role={found ? 'group' : undefined}
					aria-label={found ? describeCondition(found, field) : undefined}
					class={cn(
						'border-border inline-flex max-w-full min-w-0 items-center overflow-hidden rounded-lg border text-sm',
						CONTROL_HEIGHT[size],
						found && parts && CROSS_PAD[size],
						found ? 'bg-background' : 'text-muted-foreground max-w-72 border-dashed'
					)}
				>
					<Popover.Trigger
						disabled={disabled || !field}
						data-slot="filter-pill-trigger"
						class={cn(
							'hover:bg-muted hover:text-foreground focus-visible:ring-ring/50 inline-flex min-w-0 items-center gap-1.5 outline-none focus-visible:ring-3 focus-visible:ring-inset disabled:pointer-events-none disabled:opacity-50',
							CONTROL_HEIGHT[size],
							CONTROL_PAD[size]
						)}
					>
						{#if !found || !parts}
							<PlusIcon class={cn('shrink-0', CONTROL_GLYPH[size])} />
							<span class="min-w-0 truncate">{labelOf(name)}</span>
						{:else}
							<span data-slot="filter-pill-field" class="shrink-0 font-medium">{labelOf(name)}</span>
							{#if found.operator !== 'in'}
								<span class="text-muted-foreground shrink-0">{parts.operator}</span>
							{/if}
							{#if shown}{@render pillValues(name, shown)}{/if}
						{/if}
					</Popover.Trigger>
					{#if found && parts}
						{@render remove(name, labelOf(name))}
					{/if}
				</div>
				{@render facetList(name)}
			</Popover.Root>
		{:else if parts}
			<!-- A condition the editor wrote on an operator no checklist can hold reads as text. -->
			<div
				data-slot="filter-pill"
				data-field={name}
				data-size={size}
				data-active="true"
				role="group"
				aria-label={describeCondition(found, field)}
				class={cn(
					'border-border bg-background inline-flex max-w-full min-w-0 items-center overflow-hidden rounded-lg border text-sm',
					CONTROL_HEIGHT[size],
					CROSS_PAD[size]
				)}
			>
				<span
					class={cn('inline-flex min-w-0 items-center gap-1.5', CONTROL_HEIGHT[size], CONTROL_PAD[size])}
				>
					<span data-slot="filter-pill-field" class="shrink-0 font-medium">{labelOf(name)}</span>
					<span class="text-muted-foreground shrink-0">{parts.operator}</span>
					{#if shown}{@render pillValues(name, shown)}{/if}
				</span>
				{@render remove(name, parts.field)}
			</div>
		{/if}
	{/each}

	{#if activeCount > 0}
		<Button
			variant="ghost"
			size={CONTROL_BUTTON[size]}
			{disabled}
			class="text-muted-foreground"
			data-slot="filter-clear-all"
			onclick={() => commit(withoutPaths(value, facets))}
		>
			Clear all
		</Button>
	{/if}

	<FilterDialog
		{entityType}
		{context}
		{hidePaths}
		{disabled}
		{size}
		label="More filters"
		bind:value
		onChange={(next) => onChange?.(next)}
	/>
</div>
