// packages/react/src/registry/sg/components/picker-control.tsx
import { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react';
import type { PointerEvent as ReactPointerEvent, ReactNode, RefObject } from 'react';
import type { ChipRow, PickerSummary } from '@sg-widgets/core';
import {
  holdsArmed,
  listStatus,
  NO_MATCH_LABEL,
  pickerKeyIntent,
  scrollHighlightedIntoView,
  stateLine,
  summariseSelection,
  watchOverflow,
} from '@sg-widgets/core';
import { Combobox as ComboboxPrimitive } from '@base-ui/react';
import { Skeleton } from '@/components/ui/skeleton';
import { ChevronDown, Search, SearchX, TriangleAlert, X } from 'lucide-react';
import {
  CHIP_GAP,
  LIST_STATUS,
  OVERFLOW_RESERVE,
  PICKER_ANCHORED_POPUP,
  PICKER_BOX,
  PICKER_CONTROL,
  PICKER_GLYPH,
  PICKER_ICON_BUTTON,
  PICKER_INPUT,
  PICKER_LIST,
  PICKER_PILL,
  PICKER_POPUP,
  PICKER_ROW,
  PICKER_SEARCH,
  PICKER_SEARCH_ROW,
  PICKER_TEXT_BOX,
  PICKER_TOKEN_INPUT,
  PICKER_TRAILING,
} from '@/registry/sg/components/picker-classes';
import { StateLine } from '@/registry/sg/components/state-line';
import { cn } from '@/lib/utils';

export type PickerControlSize = 'sm' | 'md' | 'lg';

/** The row a press on the last row of a page carries, rather than an item key. */
export const LOAD_MORE = '__load-more';

/** Every chip laid out, so a hidden one still reports the width it would take. */
function measureChips(row: HTMLElement): number[] {
  const drawn = [...row.querySelectorAll<HTMLElement>('[data-chip]')];
  const was = drawn.map((chip) => chip.hidden);
  for (const chip of drawn) chip.hidden = false;
  const out = drawn.map((chip) => Math.ceil(chip.getBoundingClientRect().width) + CHIP_GAP);
  drawn.forEach((chip, i) => {
    chip.hidden = was[i] ?? false;
  });
  return out;
}

/**
 * A chip row that knows its own size: the widths once per selection and once more
 * when the fonts land, the room on every resize. `ready` is false until it knows
 * both, so the row is drawn invisible rather than in the wrong place.
 */
function useChipRow(
  active: boolean,
  rowKey: string,
  controlRef: RefObject<HTMLDivElement | null>,
  chipsRef: RefObject<HTMLSpanElement | null>,
): { fit: ChipRow | undefined; ready: boolean } {
  const [available, setAvailable] = useState(0);
  const [widths, setWidths] = useState<number[]>([]);
  const [measured, setMeasured] = useState(false);

  useLayoutEffect(() => {
    const control = controlRef.current;
    if (!active || !control) return;
    const room = (): void => {
      const style = getComputedStyle(control);
      setAvailable(control.clientWidth - parseFloat(style.paddingLeft) - parseFloat(style.paddingRight));
    };
    const observer = new ResizeObserver(room);
    observer.observe(control);
    room();
    return () => observer.disconnect();
  }, [active, controlRef]);

  useLayoutEffect(() => {
    const row = chipsRef.current;
    if (!active || !row) {
      setMeasured(false);
      return;
    }
    setWidths(measureChips(row));
    setMeasured(true);
    let live = true;
    // A chip drawn in the fallback font is not the chip the row ends up with.
    void document.fonts?.ready.then(() => {
      const current = chipsRef.current;
      if (live && current) setWidths(measureChips(current));
    });
    return () => {
      live = false;
    };
  }, [active, rowKey, chipsRef]);

  const settled = measured && available > 0;
  return {
    fit: active && settled ? { widths, available, reserve: OVERFLOW_RESERVE } : undefined,
    ready: !active || settled,
  };
}

export interface PickerControlProps {
  /** The `data-slot` prefix every part of this picker carries. */
  slot: string;
  /** The `data-picker` the popup carries. */
  picker: string;
  /** Several keys may be chosen at once. */
  multiple?: boolean;
  /** The chosen keys, in order. A single picker passes none or one. */
  keys: string[];
  /** The keys the primitive has settled on. `LOAD_MORE` never reaches it. */
  onSelect: (keys: string[]) => void;
  /** One label per chosen key: the summary, the title and the measured row read it. */
  labels: string[];
  /** The `data-slot` of the chip row. Defaults to `<slot>-chips`. */
  chipsSlot?: string;
  /** The item keys the list offers, in order. */
  items: string[];
  /** One row of the list. */
  renderItem: (key: string) => ReactNode;
  /** One chip: its index, whether Backspace has armed it, whether the row hides it. */
  renderChip?: (index: number, armed: boolean, hidden: boolean) => ReactNode;
  /** What the control shows for the selection. */
  summary?: PickerSummary;
  /** Chips drawn before the rest becomes `+n`. `0` lets the row fit what it can. */
  max?: number;
  /** The value is a measured row of chips rather than the one chip of a single picker. */
  chipRow?: boolean;
  /** The control holds the caret. A summary control keeps it in the popup instead. */
  inline?: boolean;
  /** The caret gives its room to the chips. */
  tokenInput?: boolean;
  /** What the caret shows. */
  inputPlaceholder?: string;
  /** A summary control keeps a search row. A fixed set has nothing to search. */
  searchable?: boolean;
  /** The filled value is plain text, so the control keeps the reading inset in both states. */
  textValue?: boolean;
  /** What the chips look like, so a change to any of it re-measures the row. */
  rowKey?: string;
  size?: PickerControlSize;
  disabled?: boolean;
  /** The primitive takes no input. Wider than `disabled`: a loading picker is inert too. */
  inert?: boolean;
  readonly?: boolean;
  invalid?: boolean;
  clearable?: boolean;
  placeholder?: string;
  searchPlaceholder?: string;
  /** Whether the popup is showing. */
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** What the caret holds. */
  query: string;
  onQueryChange: (query: string) => void;
  /** Remove the chip at `index`. Backspace walks the row through it. */
  onRemoveAt?: (index: number) => void;
  onClear?: () => void;
  /** The popup is as wide as the control it hangs off. */
  anchored?: boolean;
  loading?: boolean;
  error?: string | null;
  empty?: boolean;
  emptyLabel?: string;
  loadingLabel?: string;
  errorLabel?: string;
  /** A further page is there to be read. */
  hasMore?: boolean;
  onLoadMore?: () => void;
  clearLabel?: string;
  triggerLabel?: string;
  overflowLabel?: string;
  /** What the primitive writes into the input for an item. */
  itemToStringLabel?: (value: string) => string;
  /** Attributes the control carries on top of the shared ones. */
  controlProps?: React.HTMLAttributes<HTMLDivElement>;
}

/**
 * The control and the popup every picker in this registry wears.
 *
 * The box and its states, the press rule (a press anywhere on the control toggles the
 * list, the caret included), the outside-press guard, where the caret lands on
 * open, the keyboard model of core's `pickerKeyIntent`, the inline token field against
 * the summary trigger with its chip row, and the popup shell: the search row, the list,
 * the empty, loading and error block, and the load-more row. A picker supplies its rows,
 * its row renderer and its chip and nothing else.
 */
export function PickerControl({
  slot,
  picker,
  multiple = false,
  keys,
  onSelect,
  labels,
  chipsSlot,
  items,
  renderItem,
  renderChip,
  summary = 'chips',
  max = 0,
  chipRow = false,
  inline = true,
  tokenInput = true,
  inputPlaceholder,
  searchable = true,
  textValue = false,
  rowKey,
  size = 'md',
  disabled = false,
  inert = disabled,
  readonly = false,
  invalid = false,
  clearable = true,
  placeholder = '',
  searchPlaceholder = 'Search…',
  open,
  onOpenChange,
  query,
  onQueryChange,
  onRemoveAt,
  onClear,
  anchored = false,
  loading = false,
  error = null,
  empty = false,
  emptyLabel = NO_MATCH_LABEL,
  loadingLabel,
  errorLabel,
  hasMore = false,
  onLoadMore,
  clearLabel = 'Clear the selection',
  triggerLabel = 'Show the options',
  overflowLabel,
  itemToStringLabel,
  controlProps,
}: PickerControlProps) {
  const controlRef = useRef<HTMLDivElement | null>(null);
  const [listEl, setListEl] = useState<HTMLDivElement | null>(null);
  const listRef = useRef<HTMLDivElement | null>(null);
  const setList = useCallback((node: HTMLDivElement | null) => {
    listRef.current = node;
    setListEl(node);
  }, []);
  // The list writes the overflow variables the fade reads, which are Base UI's own.
  useEffect(() => watchOverflow(listEl), [listEl]);
  const inputRef = useRef<HTMLInputElement | null>(null);
  const chipsRef = useRef<HTMLSpanElement | null>(null);
  /** The chip a Backspace has highlighted. The next one removes it. */
  const [armedChip, setArmedChip] = useState<number | null>(null);
  /** A press on the load-more row is not a selection, and must not close the popup. */
  const pagingRef = useRef(false);

  const loadingText = stateLine('loading', { loadingLabel });
  const interactive = !readonly && !inert;
  const showClear = clearable && labels.length > 0 && !readonly && !disabled;
  /** Only a multi control's row weighs itself; a single one draws its chip and stops. */
  const fitted = chipRow && multiple && summary === 'ellipsis';
  const row = useChipRow(fitted, rowKey ?? `${size}|${summary}|${labels.join(', ')}`, controlRef, chipsRef);
  const plan = summariseSelection(labels, (label) => label, { summary, max, fit: row.fit });
  const counted = summary === 'count' && chipRow && multiple;
  // A chip removed from under the highlight takes it with it.
  const armed = armedChip !== null && armedChip < labels.length ? armedChip : null;
  // A chip removed from under the highlight takes it with it; a chip added later must
  // not inherit an index that outlived its chip.
  useEffect(() => {
    if (armedChip !== null && armedChip >= labels.length) setArmedChip(null);
  }, [armedChip, labels.length]);

  function setOpen(next: boolean): void {
    const wanted = interactive ? next : false;
    if (!wanted) {
      setArmedChip(null);
      onQueryChange('');
    }
    onOpenChange(wanted);
  }

  /** A press anywhere in the field opens the list, and a token field takes the caret. */
  function openFromControl(event: ReactPointerEvent<HTMLDivElement>): void {
    if (!interactive) return;
    const target = event.target as HTMLElement | null;
    // The chip's remove control, the clear control and the chevron own their own press.
    if (target?.closest('button')) return;
    const onCaret = target === inputRef.current;
    if (inline && !onCaret) {
      event.preventDefault();
      inputRef.current?.focus({ preventScroll: true });
    }
    // A press anywhere on the control toggles the list, the caret included; typing opens it again.
    setOpen(!open);
  }

  // A summary trigger has no caret of its own, so the popup's search box takes it.
  useEffect(() => {
    if (!open || inline) return;
    inputRef.current?.focus({ preventScroll: true });
  }, [open, inline]);

  // A load-more page appends rows under the highlighted one, and a new query
  // replaces them all; either way the list follows the highlight.
  useEffect(() => {
    if (!open) return;
    scrollHighlightedIntoView(listRef.current);
  }, [open, items.length]);

  /**
   * Backspace, Escape and the arrows. The primitive's own handler runs after this
   * one, so a key this picker owns is prevented rather than shared.
   */
  function onKey(event: React.KeyboardEvent<HTMLInputElement>): void {
    const intent = pickerKeyIntent(event.key, {
      open,
      query,
      count: labels.length,
      armed,
      editable: interactive,
      multiple,
    });
    if (!holdsArmed(event.key)) setArmedChip(null);
    switch (intent.kind) {
      case 'dismiss':
        setOpen(false);
        return;
      case 'arm':
        event.preventDefault();
        setArmedChip(intent.index);
        return;
      case 'remove':
        event.preventDefault();
        onRemoveAt?.(intent.index);
        return;
      case 'follow':
        // The highlight moves after this handler, so the list follows it a frame later.
        requestAnimationFrame(() => scrollHighlightedIntoView(listRef.current));
        return;
      default:
        // A closed picker leaves Escape alone: the primitive would clear the value.
        if (event.key === 'Escape') {
          (event as { preventBaseUIHandler?: () => void }).preventBaseUIHandler?.();
        }
    }
  }

  function choose(next: string[]): void {
    if (next.includes(LOAD_MORE)) {
      pagingRef.current = true;
      onLoadMore?.();
      return;
    }
    onSelect(next);
  }

  function closing(next: boolean, details: { reason?: string; event?: unknown; cancel: () => void }): void {
    // A press on a row of a multi list is a tick, not a commit: the popup stays open
    // so several rows can be ticked from one query, and paging is not a selection.
    if (!next && ((multiple && details.reason === 'item-press') || pagingRef.current)) {
      pagingRef.current = false;
      details.cancel();
      return;
    }
    // A summary control holds no input, so the click that opened it lands outside the
    // popup a moment later; a press on the control is never a dismissal.
    if (!next && details.reason === 'outside-press') {
      const target = (details.event as Event | undefined)?.target as Node | null | undefined;
      if (target && controlRef.current?.contains(target)) {
        details.cancel();
        return;
      }
    }
    setOpen(next);
  }

  const caret = (
    <ComboboxPrimitive.Input
      ref={inputRef}
      data-slot={`${slot}-input`}
      aria-invalid={invalid ? 'true' : undefined}
      aria-label={placeholder}
      readOnly={readonly || undefined}
      placeholder={inputPlaceholder ?? (labels.length > 0 ? '' : placeholder)}
      onKeyDown={onKey}
      className={tokenInput ? PICKER_TOKEN_INPUT : PICKER_INPUT}
    />
  );

  const control = (
    <div
      ref={controlRef}
      data-slot={`${slot}-control`}
      onPointerDown={openFromControl}
      role="group"
      aria-disabled={inert ? 'true' : undefined}
      data-multiple={multiple ? 'true' : undefined}
      data-invalid={invalid && !inline ? 'true' : undefined}
      data-readonly={readonly ? 'true' : undefined}
      data-empty={labels.length === 0 ? '' : undefined}
      title={plan.title || placeholder}
      className={cn(
        PICKER_CONTROL,
        (textValue ? PICKER_TEXT_BOX : PICKER_BOX)[size],
        plan.oneLine && 'flex-nowrap',
        readonly ? 'pr-3' : showClear ? 'pr-14' : 'pr-8',
      )}
      {...controlProps}
    >
      {labels.length > 0 ? (
        <span data-slot={`${slot}-value`} className="flex min-w-0 items-center gap-1.5">
          {counted ? (
            <span data-slot={`${slot}-count`} className="truncate">
              {plan.countLabel}
            </span>
          ) : chipRow ? (
            /*
              Whole chips only: the row measures itself and hides the ones that do not
              fit, so nothing is ever cut in half. `+n` follows the last one drawn.
              No stylesheet here gives `[hidden]` a display rule, so the row does.
            */
            <span
              ref={chipsRef}
              data-slot={chipsSlot ?? `${slot}-chips`}
              className={cn(
                'flex min-w-0 items-center gap-1.5 [&>[hidden]]:hidden',
                plan.oneLine ? 'flex-nowrap overflow-hidden' : 'flex-wrap',
                row.ready ? undefined : 'invisible',
              )}
            >
              {labels.map((_label, index) =>
                renderChip?.(index, armed === index, row.ready && index >= plan.shown.length),
              )}
              {plan.overflow > 0 ? (
                <button
                  type="button"
                  data-slot={`${slot}-overflow`}
                  title={plan.title}
                  aria-label={overflowLabel ?? `Show all ${labels.length} selected`}
                  onClick={() => setOpen(true)}
                  className={PICKER_PILL}
                >
                  +{plan.overflow}
                </button>
              ) : null}
            </span>
          ) : (
            renderChip?.(0, armed === 0, false)
          )}
        </span>
      ) : inline ? null : (
        <span data-slot={`${slot}-placeholder`} className="text-muted-foreground truncate">
          {placeholder}
        </span>
      )}
      {inline ? caret : null}
    </div>
  );

  let note: ReactNode = null;
  if (error !== null && error !== '') {
    note = (
      <StateLine
        state="error"
        slotName={`${slot}-error`}
        icon={TriangleAlert}
        label={stateLine('error', { errorLabel }, error)}
      />
    );
  } else if (loading) {
    note = (
      <div
        data-slot={`${slot}-loading`}
        className="flex flex-col gap-2"
        aria-busy="true"
        aria-label={loadingText}
      >
        {[0, 1, 2].map((one) => (
          <Skeleton key={one} className="h-8 w-full" />
        ))}
      </div>
    );
  } else if (empty) {
    note = <StateLine state="empty" slotName={`${slot}-empty`} icon={SearchX} label={emptyLabel} />;
  }

  function drawRow(key: string): ReactNode {
    if (key !== LOAD_MORE) return renderItem(key);
    return (
      <ComboboxPrimitive.Item
        key={LOAD_MORE}
        data-slot={`${slot}-more`}
        value={LOAD_MORE}
        className={cn(PICKER_ROW, 'text-muted-foreground justify-center text-xs')}
      >
        {loading ? loadingText : 'Load more'}
      </ComboboxPrimitive.Item>
    );
  }

  // Fixed, and anchored to the whole control rather than to the input: the list
  // scrolls its highlighted row into view on mount, and an absolute wrapper still
  // at the page origin would drag the page there with it.
  const list = (
    <ComboboxPrimitive.Portal>
      <ComboboxPrimitive.Positioner
        positionMethod="fixed"
        anchor={controlRef}
        align="start"
        sideOffset={4}
        className="isolate z-50"
      >
        <ComboboxPrimitive.Popup
          data-picker={picker}
          data-slot={`${slot}-content`}
          className={anchored ? PICKER_ANCHORED_POPUP : PICKER_POPUP}
        >
          {inline ? null : searchable ? (
            <div data-slot={`${slot}-search`} className={PICKER_SEARCH_ROW}>
              <Search aria-hidden="true" className="size-4 shrink-0 opacity-50" />
              <ComboboxPrimitive.Input
                ref={inputRef}
                data-slot={`${slot}-input`}
                aria-label={searchPlaceholder}
                placeholder={searchPlaceholder}
                onKeyDown={onKey}
                className={PICKER_SEARCH}
              />
            </div>
          ) : (
            /* Nothing to search, and still the one caret: it holds the focus and the keys. */
            <ComboboxPrimitive.Input
              ref={inputRef}
              data-slot={`${slot}-input`}
              aria-label={placeholder}
              readOnly
              onKeyDown={onKey}
              className="sr-only"
            />
          )}
          <div
            data-slot={`${slot}-status`}
            role="status"
            aria-live="polite"
            aria-atomic="true"
            className={LIST_STATUS}
          >
            {listStatus(
              { loading, count: items.length, error, asked: true },
              { emptyLabel, loadingLabel, errorLabel },
            )}
          </div>
          <ComboboxPrimitive.List ref={setList} data-slot={`${slot}-list`} className={PICKER_LIST}>
            {note ?? ((key: string) => drawRow(key))}
          </ComboboxPrimitive.List>
        </ComboboxPrimitive.Popup>
      </ComboboxPrimitive.Positioner>
    </ComboboxPrimitive.Portal>
  );

  const actions = readonly ? null : (
    <div className={cn('pointer-events-none absolute top-0 right-2 flex items-center gap-1', PICKER_TRAILING[size])}>
      {showClear ? (
        <button
          type="button"
          data-slot={`${slot}-clear`}
          aria-label={clearLabel}
          onClick={() => {
            onClear?.();
            if (inline) inputRef.current?.focus({ preventScroll: true });
          }}
          className={PICKER_ICON_BUTTON}
        >
          <X aria-hidden="true" className={PICKER_GLYPH[size]} />
        </button>
      ) : null}
      <ComboboxPrimitive.Trigger
        data-slot={`${slot}-trigger`}
        aria-label={triggerLabel}
        disabled={inert}
        className={PICKER_ICON_BUTTON}
      >
        <ChevronDown aria-hidden="true" className={PICKER_GLYPH[size]} />
      </ComboboxPrimitive.Trigger>
    </div>
  );

  const offered = hasMore ? [...items, LOAD_MORE] : items;
  const typing = (next: string, reason: string): void => {
    if (reason === 'item-press') return;
    onQueryChange(next);
    // Typing asks for the list: a press may have closed it a moment ago.
    if (reason === 'input-change' && interactive && !open) setOpen(true);
  };

  return multiple ? (
    <ComboboxPrimitive.Root
      multiple
      items={offered}
      filter={null}
      openOnInputClick={false}
      autoHighlight
      // Down stops at the last row rather than wrapping, as it does on Bits UI.
      loopFocus={false}
      disabled={inert}
      value={keys}
      onValueChange={(next) => choose(next)}
      itemToStringLabel={itemToStringLabel}
      inputValue={query}
      onInputValueChange={(next, details) => typing(next, details.reason)}
      open={open}
      onOpenChange={(next, details) => closing(next, details)}
    >
      {control}
      {list}
      {actions}
    </ComboboxPrimitive.Root>
  ) : (
    <ComboboxPrimitive.Root
      items={offered}
      filter={null}
      openOnInputClick={false}
      autoHighlight
      // Down stops at the last row rather than wrapping, as it does on Bits UI.
      loopFocus={false}
      disabled={inert}
      value={keys[0] ?? null}
      onValueChange={(next) => choose(next === null || next === undefined ? [] : [next])}
      itemToStringLabel={itemToStringLabel}
      inputValue={query}
      onInputValueChange={(next, details) => typing(next, details.reason)}
      open={open}
      onOpenChange={(next, details) => closing(next, details)}
    >
      {control}
      {list}
      {actions}
    </ComboboxPrimitive.Root>
  );
}

// packages/svelte/src/lib/registry/components/picker-control.svelte
<script lang="ts" module>
	import type { PickerSummary } from '@sg-widgets/core';

	export type PickerControlSize = 'sm' | 'md' | 'lg';

	/** The row a press on the last row of a page carries, rather than an item key. */
	export const LOAD_MORE = '__load-more';

	/** Everything a picker built on this base takes. */
	export interface PickerControlProps {
		/** The `data-slot` prefix every part of this picker carries. */
		slot: string;
		/** The `data-picker` the popup carries. */
		picker: string;
		/** Several keys may be chosen at once. */
		multiple?: boolean;
		/** The chosen keys, in order. A single picker passes none or one. */
		keys: string[];
		/** The keys the primitive has settled on. `LOAD_MORE` never reaches it. */
		onSelect: (keys: string[]) => void;
		/** One label per chosen key: the summary, the title and the measured row read it. */
		labels: string[];
		/** A stable key per chip, so a removal does not redraw the row. Defaults to the label. */
		chipKeys?: string[];
		/** The `data-slot` of the chip row. Defaults to `<slot>-chips`. */
		chipsSlot?: string;
		/** What the control shows for the selection. */
		summary?: PickerSummary;
		/** Chips drawn before the rest becomes `+n`. `0` lets the row fit what it can. */
		max?: number;
		/** The value is a measured row of chips rather than the one chip of a single picker. */
		chipRow?: boolean;
		/** The control holds the caret. A summary control keeps it in the popup instead. */
		inline?: boolean;
		/** The caret gives its room to the chips. */
		tokenInput?: boolean;
		/** What the caret shows. */
		inputPlaceholder?: string;
		/** A summary control keeps a search row. A fixed set has nothing to search. */
		searchable?: boolean;
		/** The filled value is plain text, so the control keeps the reading inset in both states. */
		textValue?: boolean;
		/** The row keys on show, so a changed list follows the highlight. */
		rowCount?: number;
		/** What the chips look like, so a change to any of it re-measures the row. */
		rowKey?: string;
		size?: PickerControlSize;
		disabled?: boolean;
		/** The primitive takes no input. Wider than `disabled`: a loading picker is inert too. */
		inert?: boolean;
		readonly?: boolean;
		invalid?: boolean;
		clearable?: boolean;
		placeholder?: string;
		searchPlaceholder?: string;
		/** Whether the popup is showing, two-way. */
		open?: boolean;
		onOpenChange?: (open: boolean) => void;
		/** What the caret holds, two-way. */
		query?: string;
		/** Remove the chip at `index`. Backspace walks the row through it. */
		onRemoveAt?: (index: number) => void;
		onClear?: () => void;
		/** The popup is as wide as the control it hangs off. */
		anchored?: boolean;
		loading?: boolean;
		/** Rows the list offers, which is what the live row counts. */
		count?: number;
		error?: string | null;
		empty?: boolean;
		emptyLabel?: string;
		loadingLabel?: string;
		errorLabel?: string;
		/** A further page is there to be read. */
		hasMore?: boolean;
		onLoadMore?: () => void;
		clearLabel?: string;
		triggerLabel?: string;
		overflowLabel?: string;
		/** Attributes the control carries on top of the shared ones. */
		controlProps?: Record<string, unknown>;
	}
</script>

<script lang="ts">
	import { tick, type Snippet } from 'svelte';
	import {
		holdsArmed,
		listStatus,
		NO_MATCH_LABEL,
		pickerKeyIntent,
		scrollHighlightedIntoView,
		stateLine,
		summariseSelection,
		watchOverflow
	} from '@sg-widgets/core';
	import { Combobox } from 'bits-ui';
	import ChevronDown from '@lucide/svelte/icons/chevron-down';
	import Search from '@lucide/svelte/icons/search';
	import SearchX from '@lucide/svelte/icons/search-x';
	import TriangleAlert from '@lucide/svelte/icons/triangle-alert';
	import X from '@lucide/svelte/icons/x';
	import { Skeleton } from '$lib/components/ui/skeleton/index.js';
	import StateLine from '$lib/registry/components/state-line.svelte';
	import {
		CHIP_GAP,
		LIST_STATUS,
		OVERFLOW_RESERVE,
		PICKER_ANCHORED_POPUP,
		PICKER_BOX,
		PICKER_CONTROL,
		PICKER_GLYPH,
		PICKER_ICON_BUTTON,
		PICKER_INPUT,
		PICKER_LIST,
		PICKER_PILL,
		PICKER_POPUP,
		PICKER_ROW,
		PICKER_SEARCH,
		PICKER_SEARCH_ROW,
		PICKER_TEXT_BOX,
		PICKER_TOKEN_INPUT,
		PICKER_TRAILING
	} from '$lib/registry/components/picker-classes.js';
	import { cn } from '$lib/utils.js';

	type Props = PickerControlProps & {
		/** One chip: its index, whether Backspace has armed it, whether the row hides it. */
		chip?: Snippet<[number, boolean, boolean]>;
		/** The rows of the list, as items of the primitive. */
		rows?: Snippet;
	};

	let {
		slot,
		picker,
		multiple = false,
		keys,
		onSelect,
		labels,
		chipKeys,
		chipsSlot,
		summary = 'chips',
		max = 0,
		chipRow = false,
		inline = true,
		tokenInput = true,
		inputPlaceholder,
		searchable = true,
		textValue = false,
		rowCount = 0,
		rowKey,
		size = 'md',
		disabled = false,
		inert = disabled,
		readonly = false,
		invalid = false,
		clearable = true,
		placeholder = '',
		searchPlaceholder = 'Search…',
		open = $bindable(false),
		onOpenChange,
		query = $bindable(''),
		onRemoveAt,
		onClear,
		anchored = false,
		loading = false,
		count = 0,
		error = null,
		empty = false,
		emptyLabel = NO_MATCH_LABEL,
		loadingLabel,
		errorLabel,
		hasMore = false,
		onLoadMore,
		clearLabel = 'Clear the selection',
		triggerLabel = 'Show the options',
		overflowLabel,
		controlProps,
		chip,
		rows
	}: Props = $props();

	let controlEl = $state<HTMLElement | null>(null);
	let listEl = $state<HTMLElement | null>(null);
	// The list writes the overflow variables the fade reads, which are Base UI's own.
	$effect(() => watchOverflow(listEl));
	let inputEl = $state<HTMLInputElement | null>(null);
	let chipsEl = $state<HTMLElement | null>(null);
	/** The chip a Backspace has highlighted. The next one removes it. */
	let armed = $state<number | null>(null);
	/** A press on the load-more row is not a selection, and must not close the popup. */
	let paging = false;

	const loadingText = $derived(stateLine('loading', { loadingLabel }));
	const interactive = $derived(!readonly && !inert);
	const showClear = $derived(clearable && labels.length > 0 && !readonly && !disabled);
	/** Only a multi control's row weighs itself; a single one draws its chip and stops. */
	const fitted = $derived(chipRow && multiple && summary === 'ellipsis');
	const measureKey = $derived(rowKey ?? `${size}|${summary}|${labels.join(', ')}`);

	let available = $state(0);
	let widths = $state<number[]>([]);
	let measured = $state(false);
	/** True once the row knows its own widths and its room, so it may be drawn. */
	const ready = $derived(!fitted || (measured && available > 0));

	/** Every chip laid out, so a hidden one still reports the width it would take. */
	function measure(row: HTMLElement): number[] {
		const drawn = [...row.querySelectorAll<HTMLElement>('[data-chip]')];
		const was = drawn.map((one) => one.hidden);
		for (const one of drawn) one.hidden = false;
		const out = drawn.map((one) => Math.ceil(one.getBoundingClientRect().width) + CHIP_GAP);
		drawn.forEach((one, i) => (one.hidden = was[i] ?? false));
		return out;
	}

	/** The room the chips have: the control's box, less the padding its affordances take. */
	function roomIn(control: HTMLElement): number {
		const style = getComputedStyle(control);
		return control.clientWidth - parseFloat(style.paddingLeft) - parseFloat(style.paddingRight);
	}

	$effect(() => {
		const control = controlEl;
		if (!control || !fitted) return;
		const observer = new ResizeObserver(() => (available = roomIn(control)));
		observer.observe(control);
		available = roomIn(control);
		return () => observer.disconnect();
	});

	$effect(() => {
		void measureKey;
		const row = chipsEl;
		if (!row || !fitted) return;
		widths = measure(row);
		measured = true;
		let live = true;
		// A chip drawn in the fallback font is not the chip the row ends up with.
		void document.fonts?.ready.then(() => {
			if (live && chipsEl) widths = measure(chipsEl);
		});
		return () => {
			live = false;
		};
	});

	const plan = $derived(
		summariseSelection(labels, (label) => label, {
			summary,
			max,
			fit: fitted && measured && available > 0 ? { widths, available, reserve: OVERFLOW_RESERVE } : undefined
		})
	);
	const counted = $derived(summary === 'count' && chipRow && multiple);

	/** A press anywhere in the field opens the list, and a token field takes the caret. */
	/** Typing asks for the list: a press may have closed it a moment ago. */
	function typed(next: string): void {
		query = next;
		if (interactive && !open) setOpen(true);
	}

	function openFromControl(event: PointerEvent): void {
		if (!interactive) return;
		const target = event.target as HTMLElement | null;
		// The chip's remove control, the clear control and the chevron own their own press.
		if (target?.closest('button')) return;
		// The press's own default would move focus to the body and off whichever caret
		// takes it: the field's, or the popup's once the effect below focuses it.
		const onCaret = target === inputEl;
		if (!onCaret) event.preventDefault();
		if (inline && !onCaret) inputEl?.focus({ preventScroll: true });
		// A press anywhere on the control toggles the list, the caret included; typing opens it again.
		setOpen(!open);
	}

	// A summary trigger has no caret of its own, so the popup's search box takes it.
	$effect(() => {
		if (!open || inline) return;
		inputEl?.focus({ preventScroll: true });
	});

	function setOpen(next: boolean): void {
		// The load-more row is a press on an item, which the primitive reads as a
		// selection. Paging is not a selection, and must not close the popup.
		if (!next && paging) {
			paging = false;
			return;
		}
		const wanted = interactive ? next : false;
		if (!wanted) {
			query = '';
			armed = null;
		}
		if (wanted === open) return;
		open = wanted;
		onOpenChange?.(open);
	}

	// A chip removed from under the highlight takes it with it.
	$effect(() => {
		if (armed !== null && armed >= labels.length) armed = null;
	});

	/**
	 * Backspace, Escape and the arrows. The primitive's own handler runs after this
	 * one, so a key this picker owns is prevented rather than shared.
	 */
	function onKey(event: KeyboardEvent): void {
		const intent = pickerKeyIntent(event.key, {
			open,
			query,
			count: labels.length,
			armed,
			editable: interactive,
			multiple
		});
		if (!holdsArmed(event.key)) armed = null;
		switch (intent.kind) {
			case 'dismiss':
				setOpen(false);
				return;
			case 'arm':
				event.preventDefault();
				armed = intent.index;
				return;
			case 'remove':
				event.preventDefault();
				onRemoveAt?.(intent.index);
				return;
			case 'follow':
				void tick().then(() => scrollHighlightedIntoView(listEl));
				return;
			default:
				return;
		}
	}

	// A load-more page appends rows under the highlighted one, and a new query
	// replaces them all; either way the list follows the highlight.
	$effect(() => {
		void rowCount;
		if (!open) return;
		void tick().then(() => scrollHighlightedIntoView(listEl));
	});

	function choose(next: string[]): void {
		if (next.includes(LOAD_MORE)) {
			paging = true;
			onLoadMore?.();
			return;
		}
		onSelect(next);
	}

	function clear(): void {
		onClear?.();
		if (inline) inputEl?.focus({ preventScroll: true });
	}
</script>

{#snippet caret()}
	<Combobox.Input
		bind:ref={inputEl}
		data-slot={`${slot}-input`}
		aria-invalid={invalid ? 'true' : undefined}
		aria-label={placeholder}
		readonly={readonly || undefined}
		placeholder={inputPlaceholder ?? (labels.length > 0 ? '' : placeholder)}
		oninput={(e) => typed(e.currentTarget.value)}
		onkeydown={onKey}
		class={tokenInput ? PICKER_TOKEN_INPUT : PICKER_INPUT}
	/>
{/snippet}

{#snippet control()}
	<div
		bind:this={controlEl}
		data-slot={`${slot}-control`}
		onpointerdown={openFromControl}
		role="group"
		aria-disabled={inert ? 'true' : undefined}
		data-multiple={multiple ? 'true' : undefined}
		data-invalid={invalid && !inline ? 'true' : undefined}
		data-readonly={readonly ? 'true' : undefined}
		data-empty={labels.length === 0 ? '' : undefined}
		title={plan.title || placeholder}
		class={cn(
			PICKER_CONTROL,
			(textValue ? PICKER_TEXT_BOX : PICKER_BOX)[size],
			plan.oneLine && 'flex-nowrap',
			readonly ? 'pr-3' : showClear ? 'pr-14' : 'pr-8'
		)}
		{...controlProps}
	>
		{#if labels.length > 0}
			<span data-slot={`${slot}-value`} class="flex min-w-0 items-center gap-1.5">
				{#if counted}
					<span data-slot={`${slot}-count`} class="truncate">{plan.countLabel}</span>
				{:else if chipRow}
					<!--
						Whole chips only: the row measures itself and hides the ones that do not
						fit, so nothing is ever cut in half. `+n` follows the last one drawn.
						No stylesheet here gives `[hidden]` a display rule, so the row does.
					-->
					<span
						bind:this={chipsEl}
						data-slot={chipsSlot ?? `${slot}-chips`}
						class={cn(
							'flex min-w-0 items-center gap-1.5 [&>[hidden]]:hidden',
							plan.oneLine ? 'flex-nowrap overflow-hidden' : 'flex-wrap',
							ready ? undefined : 'invisible'
						)}
					>
						{#each labels as label, index (chipKeys?.[index] ?? `${index}:${label}`)}
							{@render chip?.(index, armed === index, ready && index >= plan.shown.length)}
						{/each}
						{#if plan.overflow > 0}
							<button
								type="button"
								data-slot={`${slot}-overflow`}
								title={plan.title}
								aria-label={overflowLabel ?? `Show all ${labels.length} selected`}
								onclick={() => setOpen(true)}
								class={PICKER_PILL}>+{plan.overflow}</button
							>
						{/if}
					</span>
				{:else}
					{@render chip?.(0, armed === 0, false)}
				{/if}
			</span>
		{:else if !inline}
			<span data-slot={`${slot}-placeholder`} class="text-muted-foreground truncate">{placeholder}</span>
		{/if}
		{#if inline}
			{@render caret()}
		{/if}
	</div>
{/snippet}

{#snippet popup()}
	<!--
		Fixed, and anchored to the whole control rather than to the input: the list
		scrolls its highlighted row into view on mount, and an absolute wrapper still
		at the page origin would drag the page there with it.
	-->
	<Combobox.Portal>
		<Combobox.Content
			data-picker={picker}
			data-slot={`${slot}-content`}
			strategy="fixed"
			customAnchor={controlEl}
			align="start"
			sideOffset={4}
			class={anchored ? PICKER_ANCHORED_POPUP : PICKER_POPUP}
		>
			{#if !inline && searchable}
				<div data-slot={`${slot}-search`} class={PICKER_SEARCH_ROW}>
					<Search aria-hidden="true" class="size-4 shrink-0 opacity-50" />
					<Combobox.Input
						bind:ref={inputEl}
						data-slot={`${slot}-input`}
						aria-label={searchPlaceholder}
						placeholder={searchPlaceholder}
						oninput={(e) => typed(e.currentTarget.value)}
						onkeydown={onKey}
						class={PICKER_SEARCH}
					/>
				</div>
			{:else if !inline}
				<!-- Nothing to search, and still the one caret: it holds the focus and the keys. -->
				<Combobox.Input
					bind:ref={inputEl}
					data-slot={`${slot}-input`}
					aria-label={placeholder}
					readonly
					onkeydown={onKey}
					class="sr-only"
				/>
			{/if}
			<div
				data-slot={`${slot}-status`}
				role="status"
				aria-live="polite"
				aria-atomic="true"
				class={LIST_STATUS}
			>
				{listStatus({ loading, count, error, asked: true }, { emptyLabel, loadingLabel, errorLabel })}
			</div>
			<div bind:this={listEl} data-slot={`${slot}-list`} class={PICKER_LIST}>
				{#if error !== null && error !== ''}
					<StateLine
						state="error"
						slotName={`${slot}-error`}
						icon={TriangleAlert}
						label={stateLine('error', { errorLabel }, error)}
					/>
				{:else if loading}
					<div
						data-slot={`${slot}-loading`}
						class="flex flex-col"
						aria-busy="true"
						aria-label={loadingText}
					>
						{#each [0, 1, 2] as row (row)}
							<div class="flex items-center px-2 py-1.5">
								<Skeleton class="h-5 w-full" />
							</div>
						{/each}
					</div>
				{:else if empty}
					<StateLine state="empty" slotName={`${slot}-empty`} icon={SearchX} label={emptyLabel} />
				{:else}
					{@render rows?.()}
					{#if hasMore}
						<Combobox.Item
							data-slot={`${slot}-more`}
							value={LOAD_MORE}
							label={loading ? loadingText : 'Load more'}
							class={cn(PICKER_ROW, 'text-muted-foreground justify-center text-xs')}
						>
							{loading ? loadingText : 'Load more'}
						</Combobox.Item>
					{/if}
				{/if}
			</div>
		</Combobox.Content>
	</Combobox.Portal>
{/snippet}

{#snippet actions()}
	{#if !readonly}
		<div class={cn('pointer-events-none absolute top-0 right-2 flex items-center gap-1', PICKER_TRAILING[size])}>
			{#if showClear}
				<button
					type="button"
					data-slot={`${slot}-clear`}
					aria-label={clearLabel}
					onclick={clear}
					class={PICKER_ICON_BUTTON}
				>
					<X aria-hidden="true" class={PICKER_GLYPH[size]} />
				</button>
			{/if}
			<Combobox.Trigger
				data-slot={`${slot}-trigger`}
				aria-label={triggerLabel}
				disabled={inert}
				class={PICKER_ICON_BUTTON}
			>
				<ChevronDown aria-hidden="true" class={PICKER_GLYPH[size]} />
			</Combobox.Trigger>
		</div>
	{/if}
{/snippet}

<!--
	The control and the popup every picker in this registry wears.

	The box and its states, the press rule (a press anywhere on the control toggles the
	list, the caret included), where the caret lands on open, the keyboard model
	of core's `pickerKeyIntent`, the inline token field against the summary trigger with
	its chip row, and the popup shell: the search row, the list, the empty, loading and
	error block, and the load-more row. A picker supplies its rows, its row renderer and
	its chip and nothing else.
-->
{#if multiple}
	<Combobox.Root
		type="multiple"
		disabled={inert}
		inputValue={query}
		bind:open={() => open, setOpen}
		bind:value={() => keys, choose}
	>
		{@render control()}
		{@render popup()}
		{@render actions()}
	</Combobox.Root>
{:else}
	<Combobox.Root
		type="single"
		allowDeselect={false}
		disabled={inert}
		inputValue={query}
		bind:open={() => open, setOpen}
		bind:value={() => keys[0] ?? '', (key) => choose(key === '' ? [] : [key])}
	>
		{@render control()}
		{@render popup()}
		{@render actions()}
	</Combobox.Root>
{/if}
