// packages/svelte/src/lib/registry/components/filter-editor.svelte
<script lang="ts" module>
	import type { Snippet } from 'svelte';

	export type FilterEditorSize = 'sm' | 'md' | 'lg';

	/** A condition row is a control inside a control, so its ladder sits one step down. */
	const BOX: Record<FilterEditorSize, string> = { sm: 'h-7', md: 'h-8', lg: 'h-9' };
	const INNER: Record<FilterEditorSize, 'sm' | 'md'> = { sm: 'sm', md: 'sm', lg: 'md' };
	const BTN: Record<FilterEditorSize, 'xs' | 'sm' | 'default'> = { sm: 'xs', md: 'sm', lg: 'default' };
	const ICON: Record<FilterEditorSize, 'icon-xs' | 'icon-sm' | 'icon'> = {
		sm: 'icon-xs',
		md: 'icon-sm',
		lg: 'icon'
	};
	const TOGGLE: Record<FilterEditorSize, 'sm' | 'default'> = { sm: 'sm', md: 'sm', lg: 'default' };
	import type {
		ConditionValue,
		EntityRef,
		FieldSchema,
		FilterCondition,
		FilterGroup,
		FilterNode,
		NodePath,
		Operator,
		Scalar
	} from '@sg-widgets/core';

	/** What the field slot is given. Its job is to call `onSelect` with a dotted path. */
	export interface FieldChooserArgs {
		entityType: string;
		/** The path the row holds now, empty on a new row. */
		path: string;
		hidePaths: string[];
		/** Only fields the API can filter on. Always true here. */
		filterableOnly: true;
		disabled: boolean;
		onSelect: (path: string) => void;
	}

	/** What a value slot is given. Its job is to call `onChange` with the value the operator expects. */
	export interface ValueEditorArgs {
		field: FieldSchema | null;
		dataType: string;
		operator: Operator;
		value: ConditionValue;
		/** The arity the operator's wire shape asks for. */
		arity: 'none' | 'one' | 'many' | 'two' | 'relative';
		disabled: boolean;
		onChange: (value: ConditionValue) => void;
	}

	/** The six types NumberEditor parses. `footage` is numeric to the API and reads as a plain number. */
	const NUMERIC_EDITORS = ['number', 'float', 'percent', 'duration', 'timecode', 'currency'] as const;
	type NumericEditor = (typeof NUMERIC_EDITORS)[number];

	function numericType(dataType: string): NumericEditor {
		return (NUMERIC_EDITORS as readonly string[]).includes(dataType) ? (dataType as NumericEditor) : 'number';
	}

	function textValue(value: Scalar | undefined): string | null {
		if (value === null || value === undefined) return null;
		return typeof value === 'object' ? null : String(value);
	}

	function numberValue(value: Scalar | undefined): number | string | null {
		if (value === null || value === undefined || value === '') return null;
		return typeof value === 'number' || typeof value === 'string' ? value : null;
	}

	function codes(value: ConditionValue): string[] {
		if (!Array.isArray(value)) return [];
		return (value as Scalar[]).filter((v): v is string => typeof v === 'string');
	}

	/** `is` takes one entity hash and `in` a list of them; a list under `is` is a 400 (field_types/entity). */
	function entityRefs(value: ConditionValue): EntityRef[] {
		if (Array.isArray(value)) return value.filter((v) => v !== null && typeof v === 'object') as EntityRef[];
		return value !== null && typeof value === 'object' ? [value as EntityRef] : [];
	}

	function entityRef(value: ConditionValue): EntityRef | null {
		return value !== null && typeof value === 'object' && !Array.isArray(value) ? (value as EntityRef) : null;
	}

	/** Every dotted path the tree holds. A flat name needs no resolution. */
	function dottedPaths(node: FilterNode, out: string[] = []): string[] {
		if (node.kind === 'condition') {
			if (node.path.includes('.')) out.push(node.path);
			return out;
		}
		for (const child of node.conditions) dottedPaths(child, out);
		return out;
	}
</script>

<script lang="ts">
	import PlusIcon from '@lucide/svelte/icons/plus';
	import XIcon from '@lucide/svelte/icons/x';
	import type { HTMLAttributes } from 'svelte/elements';
	import type { SgContext, TimeUnit } from '@sg-widgets/core';
	import {
		appendAt,
		applyPreset,
		condition as makeCondition,
		conditionArity,
		conditionList,
		defaultCondition,
		emptyFilter,
		group as makeGroup,
		NOTHING_CHOSEN_LABEL,
		operatorMenu,
		presetById,
		presetIdOf,
		relativeWindow,
		removeAt,
		replaceAt,
		timeUnitField,
		valueEditorFor,
		withAddedListValue,
		withListValue,
		withoutListValue,
		withRelativeWindow
	} from '@sg-widgets/core';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Select from '$lib/components/ui/select/index.js';
	import { Skeleton } from '$lib/components/ui/skeleton/index.js';
	import * as ToggleGroup from '$lib/components/ui/toggle-group/index.js';
	import { cn, type WithElementRef } from '$lib/utils.js';
	import { entityFields } from '$lib/registry/components/entity-fields.svelte.js';
	import CheckboxEditor from '$lib/registry/components/checkbox-editor.svelte';
	import StateLine from '$lib/registry/components/state-line.svelte';
	import ColorEditor from '$lib/registry/components/color-editor.svelte';
	import DateEditor from '$lib/registry/components/date-editor.svelte';
	import DateTimeEditor from '$lib/registry/components/date-time-editor.svelte';
	import EntityMultiPicker from '$lib/registry/components/entity-multi-picker.svelte';
	import EntityPicker from '$lib/registry/components/entity-picker.svelte';
	import FieldPicker from '$lib/registry/components/field-picker.svelte';
	import ListMultiSelect from '$lib/registry/components/list-multi-select.svelte';
	import ListSelect from '$lib/registry/components/list-select.svelte';
	import NumberEditor from '$lib/registry/components/number-editor.svelte';
	import StatusMultiPicker from '$lib/registry/components/status-multi-picker.svelte';
	import StatusPicker from '$lib/registry/components/status-picker.svelte';
	import TextEditor from '$lib/registry/components/text-editor.svelte';
	import UrlEditor from '$lib/registry/components/url-editor.svelte';

	type Props = WithElementRef<HTMLAttributes<HTMLDivElement>, HTMLDivElement> & {
		/** Type the root of every field path is read on. */
		entityType: string;
		/** The widget context. Every read goes through it, so widgets on a page share one cache. */
		context: SgContext;
		value: FilterGroup;
		/** Paths to keep out of the field list, each hiding itself and everything under it. */
		hidePaths?: string[];
		/** Scopes the status pickers to the codes one project allows. */
		projectId?: number;
		/** Shown when a group holds no condition. */
		emptyLabel?: string;
		size?: FilterEditorSize;
		disabled?: boolean;
		onChange?: (value: FilterGroup) => void;
		fieldChooser?: Snippet<[FieldChooserArgs]>;
		valueEditor?: Snippet<[ValueEditorArgs]>;
		entityEditor?: Snippet<[ValueEditorArgs]>;
		class?: string;
	};

	let {
		entityType,
		context,
		value = $bindable(emptyFilter()),
		hidePaths = [],
		projectId,
		emptyLabel = NOTHING_CHOSEN_LABEL,
		size = 'md',
		disabled = false,
		onChange,
		fieldChooser,
		valueEditor,
		entityEditor,
		class: className,
		ref = $bindable(null),
		...rest
	}: Props = $props();

	const schemaFields = entityFields(
		() => context,
		() => entityType
	);
	const fields = $derived(schemaFields.current);

	/**
	 * The leaf schema of every dotted path the tree holds, added once and kept.
	 * `resolving` is a plain map, so filling the cache never re-triggers the walk.
	 */
	let leaves = $state<Record<string, FieldSchema | null>>({});
	const resolving = new Map<string, Promise<FieldSchema | null>>();

	function leafKey(path: string): string {
		return `${entityType}|${path}`;
	}

	function resolveLeaf(path: string): Promise<FieldSchema | null> {
		const key = leafKey(path);
		let job = resolving.get(key);
		if (!job) {
			job = context.schema.resolvePath(entityType, path).then(
				(segments) => segments[segments.length - 1]?.field ?? null,
				// A path the schema no longer holds still has to be editable, so the row keeps it.
				() => null
			);
			resolving.set(key, job);
			void job.then((leaf) => {
				leaves = { ...leaves, [key]: leaf };
			});
		}
		return job;
	}

	$effect(() => {
		for (const path of dottedPaths(value)) void resolveLeaf(path);
	});

	/** The leaf field of a path. A flat name is a field of the root type. */
	function fieldOf(path: string): FieldSchema | null {
		if (!path) return null;
		if (!path.includes('.')) return fields[path] ?? null;
		return leaves[leafKey(path)] ?? null;
	}

	function dataTypeOf(path: string): string {
		return fieldOf(path)?.dataType ?? '';
	}

	/** True while a dotted path is still being walked; its leaf decides the whole row. */
	function unresolved(path: string): boolean {
		return path.includes('.') && !(leafKey(path) in leaves);
	}

	function commit(next: FilterGroup): void {
		value = next;
		onChange?.(next);
	}

	function edit(path: NodePath, node: FilterCondition | FilterGroup): void {
		commit(replaceAt(value, path, node));
	}

	async function pickField(path: NodePath, current: FilterCondition, chosen: string): Promise<void> {
		const before = dataTypeOf(current.path);
		const after = chosen.includes('.') ? ((await resolveLeaf(chosen))?.dataType ?? '') : dataTypeOf(chosen);
		// The operator vocabulary is per data type, so moving to another type resets the row.
		edit(path, before === after && current.path ? { ...current, path: chosen } : defaultCondition(chosen, after));
	}

	function pickPreset(path: NodePath, current: FilterCondition, id: string): void {
		const dataType = dataTypeOf(current.path);
		const preset = presetById(dataType, id);
		if (preset) edit(path, applyPreset(current, preset, dataType));
	}
</script>

{#snippet fieldSlot(path: NodePath, node: FilterCondition)}
	<!-- The field is the row's widest cell: it takes 14rem, truncates, and gives the rest back. -->
	<div data-slot="filter-field" class="min-w-24 max-w-56 grow basis-24">
		{#if fieldChooser}
			{@render fieldChooser({
				entityType,
				path: node.path,
				hidePaths,
				filterableOnly: true,
				disabled,
				onSelect: (next: string) => void pickField(path, node, next)
			})}
		{:else}
			<FieldPicker
				{context}
				{entityType}
				{hidePaths}
				{disabled}
				value={node.path}
				deepLinks
				filterableOnly
				clearable={false}
				size={INNER[size]}
				placeholder="Select a field"
				onValueChange={(next) => void pickField(path, node, next)}
			/>
		{/if}
	</div>
{/snippet}

{#snippet operatorSlot(path: NodePath, node: FilterCondition)}
	{@const dataType = dataTypeOf(node.path)}
	{@const menu = operatorMenu(dataType)}
	{@const current = presetIdOf(node, dataType)}
	<Select.Root
		type="single"
		value={current}
		disabled={disabled || menu.length === 0}
		onValueChange={(id) => pickPreset(path, node, id)}
	>
		<Select.Trigger class={cn(BOX[size], 'w-40 shrink-0')} data-slot="filter-operator">
			{presetById(dataType, current)?.label ?? current}
		</Select.Trigger>
		<Select.Content>
			{#each menu as run (run.label)}
				<Select.Group>
					<Select.GroupHeading>{run.label}</Select.GroupHeading>
					{#each run.presets as preset (preset.id)}
						<Select.Item value={preset.id} label={preset.label} data-preset={preset.id} />
					{/each}
				</Select.Group>
			{/each}
		</Select.Content>
	</Select.Root>
{/snippet}

<!--
	A value editor sized for a row. The typed types take the width their content needs and
	the free width goes to the ones that hold a name: a date, a time and a number never
	push the row onto a second line.
-->
{#snippet scalarEditor(kind: string, dataType: string, label: string, current: Scalar, set: (v: Scalar) => void)}
	{#if kind === 'number'}
		<NumberEditor
			class="shrink-0"
			size={INNER[size]}
			inline
			{disabled}
			dataType={numericType(dataType)}
			field={{ displayName: label, mandatory: false }}
			value={numberValue(current)}
			onValueChange={(next) => set(next ?? '')}
		/>
	{:else if kind === 'date'}
		<DateEditor
			class="shrink-0"
			size={INNER[size]}
			inline
			{disabled}
			field={{ displayName: label, mandatory: false }}
			value={textValue(current)}
			onValueChange={(next) => set(next ?? '')}
		/>
	{:else if kind === 'date_time'}
		<DateTimeEditor
			class="shrink-0"
			size={INNER[size]}
			inline
			hint={false}
			{disabled}
			field={{ displayName: label, mandatory: false }}
			value={textValue(current)}
			onValueChange={(next) => set(next ?? '')}
		/>
	{:else if kind === 'color'}
		<ColorEditor
			class="w-44 shrink-0"
			size={INNER[size]}
			hint={false}
			{disabled}
			field={{ displayName: label, mandatory: false }}
			value={textValue(current)}
			onValueChange={(next) => set(next ?? '')}
		/>
	{:else if kind === 'url'}
		<!-- The row compares the link itself, so the editor's name half is left out of the value. -->
		<UrlEditor
			class="min-w-0 flex-1"
			size={INNER[size]}
			{disabled}
			field={{ displayName: label, mandatory: false }}
			value={textValue(current) ? { url: String(textValue(current)) } : null}
			onValueChange={(next) => set(next?.url ?? '')}
		/>
	{:else}
		<TextEditor
			class="min-w-0 flex-1"
			size={INNER[size]}
			{disabled}
			field={{ displayName: label, mandatory: false }}
			value={textValue(current)}
			onValueChange={(next) => set(next ?? '')}
		/>
	{/if}
{/snippet}

<!--
	A list of values, one to a line, each edited by its own data type's control and each
	with the control that drops it. The arity is the operator's: `in` and `not_in` take a
	JSON array, and a blank value is dropped on serialisation rather than sent.
-->
{#snippet listEditor(kind: string, dataType: string, label: string, current: ConditionValue, set: (v: ConditionValue) => void)}
	{@const items = conditionList(current)}
	<div class="flex min-w-0 flex-1 flex-col items-start gap-2" data-slot="filter-list">
		{#each items as item, i (i)}
			<div class="flex min-w-0 items-center gap-1.5" data-slot="filter-list-value" data-index={i}>
				{@render scalarEditor(kind, dataType, label, item, (v) =>
					set(withListValue(current, i, v) as ConditionValue)
				)}
				<Button
					variant="ghost"
					size={ICON[size]}
					class="text-muted-foreground hover:text-foreground shrink-0"
					{disabled}
					aria-label="Remove value"
					data-slot="filter-list-remove"
					onclick={() => set(withoutListValue(current, i) as ConditionValue)}
				>
					<XIcon />
				</Button>
			</div>
		{/each}
		<Button
			variant="ghost"
			size={BTN[size]}
			class="text-muted-foreground hover:text-foreground shrink-0"
			{disabled}
			data-slot="filter-list-add"
			onclick={() => set(withAddedListValue(current) as ConditionValue)}
		>
			<PlusIcon />
			Value
		</Button>
	</div>
{/snippet}

{#snippet entityValue(field: FieldSchema | null, arity: string, current: ConditionValue, set: (v: ConditionValue) => void)}
	{@const types = field?.validTypes?.length ? field.validTypes : [entityType]}
	{#if arity === 'many'}
		<EntityMultiPicker
			class="min-w-0 flex-1"
			size={INNER[size]}
			{context}
			{disabled}
			{projectId}
			entityTypes={types}
			placeholder="Search entities"
			value={entityRefs(current)}
			onValueChange={(next) => set([...next])}
		/>
	{:else}
		<EntityPicker
			class="min-w-0 flex-1"
			size={INNER[size]}
			{context}
			{disabled}
			{projectId}
			entityTypes={types}
			placeholder="Search entities"
			value={entityRef(current)}
			onValueChange={(next) => set(next ?? '')}
		/>
	{/if}
{/snippet}

{#snippet valueSlot(path: NodePath, node: FilterCondition)}
	{@const field = fieldOf(node.path)}
	{@const dataType = field?.dataType ?? ''}
	{@const kind = valueEditorFor(dataType, node.operator)}
	{@const arity = conditionArity(node, dataType)}
	{@const set = (v: ConditionValue) => edit(path, { ...node, value: v })}
	<div class="flex min-w-40 flex-1 flex-wrap items-center gap-2" data-slot="filter-value">
		{#if unresolved(node.path)}
			<Skeleton class={cn(BOX[size], 'min-w-0 flex-1')} />
		{:else if valueEditor}
			<!-- Integration point: a caller's own editors replace every one below. -->
			{@render valueEditor({
				field,
				dataType,
				operator: node.operator,
				value: node.value,
				arity,
				disabled,
				onChange: set
			})}
		{:else if arity === 'none'}
			<!-- `is empty` and the calendar presets pin their value; there is nothing to edit. -->
		{:else if arity === 'relative'}
			{@const window_ = relativeWindow(node.value)}
			<!-- A window is a count and a unit: the number editor and the list a `list` field uses. -->
			<div class="flex min-w-0 shrink-0 items-center gap-2" data-slot="filter-window">
				<NumberEditor
					class="w-16 shrink-0"
					size={INNER[size]}
					inline
					{disabled}
					dataType="number"
					min={1}
					field={{ displayName: 'Count', mandatory: true }}
					value={window_.count}
					onValueChange={(next) =>
						set(withRelativeWindow(node.value, { count: next === null ? null : Number(next) }) as ConditionValue)}
				/>
				<ListSelect
					class="w-24 shrink-0"
					size={INNER[size]}
					{disabled}
					field={timeUnitField()}
					value={window_.unit}
					onValueChange={(next) =>
						set(withRelativeWindow(node.value, { unit: (next ?? 'DAY') as TimeUnit }) as ConditionValue)}
				/>
			</div>
		{:else if kind === 'entity'}
			{#if entityEditor}
				<!-- Integration point: EntityMultiPicker plugs in here. -->
				{@render entityEditor({
					field,
					dataType,
					operator: node.operator,
					value: node.value,
					arity,
					disabled,
					onChange: set
				})}
			{:else}
				{@render entityValue(field, arity, node.value, set)}
			{/if}
		{:else if kind === 'checkbox'}
			<CheckboxEditor
				class="min-w-0 flex-1"
				size={INNER[size]}
				{disabled}
				field={{ displayName: field?.displayName ?? 'Value', mandatory: false }}
				value={node.value === true}
				onValueChange={(next) => set(next)}
			/>
		{:else if kind === 'options' && dataType === 'status_list' && arity === 'many'}
			<StatusMultiPicker
				class="min-w-0 flex-1"
				size={INNER[size]}
				{context}
				{disabled}
				{projectId}
				entityType={field?.entityType ?? entityType}
				field={field?.name}
				value={codes(node.value)}
				onValueChange={(next) => set([...next])}
			/>
		{:else if kind === 'options' && dataType === 'status_list'}
			<StatusPicker
				class="min-w-0 flex-1"
				size={INNER[size]}
				{context}
				{disabled}
				{projectId}
				entityType={field?.entityType ?? entityType}
				field={field?.name}
				value={typeof node.value === 'string' && node.value !== '' ? node.value : undefined}
				onValueChange={(next) => set(next ?? '')}
			/>
		{:else if kind === 'options' && arity === 'many'}
			<ListMultiSelect
				class="min-w-0 flex-1"
				size={INNER[size]}
				{disabled}
				{field}
				placeholder="Select values…"
				value={codes(node.value)}
				onValueChange={(next) => set([...next])}
			/>
		{:else if kind === 'options'}
			<ListSelect
				class="min-w-0 flex-1"
				size={INNER[size]}
				{disabled}
				{field}
				placeholder="Select a value…"
				value={typeof node.value === 'string' && node.value !== '' ? node.value : null}
				onValueChange={(next) => set(next ?? '')}
			/>
		{:else if arity === 'two'}
			{@const pair = (Array.isArray(node.value) ? node.value : [null, null]) as [Scalar, Scalar]}
			<!-- Both ends on one line, joined by the word that reads the range. -->
			<div class="flex min-w-0 flex-1 flex-wrap items-center gap-2" data-slot="filter-range">
				{@render scalarEditor(kind, dataType, 'From', pair[0], (v) => set([v, pair[1]] as ConditionValue))}
				<span class="text-muted-foreground shrink-0 text-sm">and</span>
				{@render scalarEditor(kind, dataType, 'To', pair[1], (v) => set([pair[0], v] as ConditionValue))}
			</div>
		{:else if arity === 'many'}
			{@render listEditor(kind, dataType, field?.displayName ?? 'Value', node.value, set)}
		{:else}
			{@render scalarEditor(kind, dataType, field?.displayName ?? 'Value', node.value as Scalar, (v) => set(v))}
		{/if}
	</div>
{/snippet}

<!--
	A row is two bands: the field, the operator and the value on one 36px line, and
	the remove button on its own. The remove sits outside the wrapping band, so it
	holds the same vertical axis at every depth and never costs the row a line.
-->
{#snippet conditionRow(path: NodePath, node: FilterCondition)}
	<div class="flex min-h-9 min-w-0 items-center gap-2" data-slot="filter-row" data-path={path.join('.')}>
		<div class="flex min-w-0 flex-1 flex-wrap items-center gap-2" data-slot="filter-row-content">
			{@render fieldSlot(path, node)}
			{@render operatorSlot(path, node)}
			{@render valueSlot(path, node)}
		</div>
		<Button
			variant="ghost"
			size={ICON[size]}
			class="text-muted-foreground hover:text-foreground mt-1 shrink-0 self-start"
			{disabled}
			aria-label="Remove condition"
			data-slot="filter-remove"
			onclick={() => commit(removeAt(value, path))}
		>
			<XIcon />
		</Button>
	</div>
{/snippet}

<!--
	A group is a header, its rows and a foot. The header says how the rows join and
	removes the group; the rows hang off one rail, so a level of nesting is one
	indent; the foot is where rows and groups are added.
-->
{#snippet groupNode(path: NodePath, node: FilterGroup)}
	{@const depth = path.length}
	<div
		class={cn('flex min-w-0 flex-col gap-2', depth > 0 && 'bg-muted/40 rounded-lg p-2')}
		data-slot="filter-group"
		data-path={path.join('.')}
		data-depth={depth}
		data-logical-operator={node.logicalOperator}
	>
		<div class="flex min-h-9 min-w-0 items-center gap-2" data-slot="filter-group-header">
			<ToggleGroup.Root
				type="single"
				size={TOGGLE[size]}
				variant="outline"
				{disabled}
				value={node.logicalOperator}
				data-slot="filter-logic"
				onValueChange={(next) =>
					next && edit(path, { ...node, logicalOperator: next as FilterGroup['logicalOperator'] })}
			>
				<ToggleGroup.Item value="and" aria-label="Match all">All</ToggleGroup.Item>
				<ToggleGroup.Item value="or" aria-label="Match any">Any</ToggleGroup.Item>
			</ToggleGroup.Root>
			<span class="text-muted-foreground min-w-0 flex-1 truncate text-xs">of these match</span>
			{#if depth > 0}
				<Button
					variant="ghost"
					size={ICON[size]}
					class="text-muted-foreground hover:text-foreground mt-1 shrink-0 self-start"
					{disabled}
					aria-label="Remove group"
					data-slot="filter-remove"
					onclick={() => commit(removeAt(value, path))}
				>
					<XIcon />
				</Button>
			{/if}
		</div>
		<div
			class="border-border flex min-w-0 flex-col gap-2 border-l pl-3"
			data-slot="filter-group-body"
		>
			{#each node.conditions as child, i (i)}
				{#if child.kind === 'group'}
					{@render groupNode([...path, i], child)}
				{:else}
					{@render conditionRow([...path, i], child)}
				{/if}
			{/each}
			{#if node.conditions.length === 0}
				<StateLine state="empty" slotName="filter-group-empty" label={emptyLabel} />
			{/if}
		</div>
		<div class="flex min-w-0 flex-wrap items-center gap-1 pl-3" data-slot="filter-foot">
			<Button
				variant="ghost"
				size={BTN[size]}
				class="text-muted-foreground hover:text-foreground"
				{disabled}
				data-slot="filter-add-condition"
				data-path={path.join('.')}
				onclick={() => commit(appendAt(value, path, makeCondition('', 'is', '')))}
			>
				<PlusIcon />
				Condition
			</Button>
			<Button
				variant="ghost"
				size={BTN[size]}
				class="text-muted-foreground hover:text-foreground"
				{disabled}
				data-slot="filter-add-group"
				data-path={path.join('.')}
				onclick={() => commit(appendAt(value, path, makeGroup('or')))}
			>
				<PlusIcon />
				Group
			</Button>
		</div>
	</div>
{/snippet}

<!--
	A filter tree, edited.

	A row is a field, an operator and a value; a group nests rows under `All` or
	`Any`. The operator menu and the value editor both come from the field's
	`data_type` through core, so a row can only build a filter the API accepts
	(017_filter_operators). A row with no field, or one whose operator still has no
	value, is dropped on serialisation rather than sent.

	The field is chosen with FieldPicker, which descends through links, so a row may
	filter on a dotted path; the leaf of that path is resolved through the schema
	service and is what picks the operator menu and the value editor. An operator that
	pins its value draws no editor at all.
-->
<div
	bind:this={ref}
	data-slot="filter-editor"
	data-entity-type={entityType}
	aria-disabled={disabled ? 'true' : undefined}
	class={cn('flex w-full min-w-0 flex-col gap-3', disabled && 'opacity-50', className)}
	{...rest}
>
	{@render groupNode([], value)}
</div>

// packages/react/src/registry/sg/components/filter-editor.tsx
import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import type {
  ConditionValue,
  EntityRef,
  FieldSchema,
  FilterCondition,
  FilterGroup,
  FilterNode,
  NodePath,
  Operator,
  Scalar,
  SgContext,
  TimeUnit,
} from '@sg-widgets/core';
import {
  appendAt,
  applyPreset,
  condition as makeCondition,
  conditionArity,
  conditionList,
  defaultCondition,
  emptyFilter,
  group as makeGroup,
  NOTHING_CHOSEN_LABEL,
  operatorMenu,
  presetById,
  presetIdOf,
  relativeWindow,
  removeAt,
  replaceAt,
  timeUnitField,
  valueEditorFor,
  withAddedListValue,
  withListValue,
  withoutListValue,
  withRelativeWindow,
} from '@sg-widgets/core';
import { PlusIcon, XIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
} from '@/components/ui/select';
import { Skeleton } from '@/components/ui/skeleton';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { cn } from '@/lib/utils';
import { CheckboxEditor } from '@/registry/sg/components/checkbox-editor';
import { ColorEditor } from '@/registry/sg/components/color-editor';
import { DateEditor } from '@/registry/sg/components/date-editor';
import { DateTimeEditor } from '@/registry/sg/components/date-time-editor';
import { useEntityFields } from '@/registry/sg/components/entity-fields';
import { EntityMultiPicker } from '@/registry/sg/components/entity-multi-picker';
import { EntityPicker } from '@/registry/sg/components/entity-picker';
import { FieldPicker } from '@/registry/sg/components/field-picker';
import { ListMultiPicker } from '@/registry/sg/components/list-multi-picker';
import { ListPicker } from '@/registry/sg/components/list-picker';
import { NumberEditor } from '@/registry/sg/components/number-editor';
import { StateLine } from '@/registry/sg/components/state-line';
import { StatusMultiPicker } from '@/registry/sg/components/status-multi-picker';
import { StatusPicker } from '@/registry/sg/components/status-picker';
import { TextEditor } from '@/registry/sg/components/text-editor';
import { UrlEditor } from '@/registry/sg/components/url-editor';

/** What the field slot is given. Its job is to call `onSelect` with a dotted path. */
export interface FieldChooserArgs {
  entityType: string;
  /** The path the row holds now, empty on a new row. */
  path: string;
  hidePaths: string[];
  /** Only fields the API can filter on. Always true here. */
  filterableOnly: true;
  disabled: boolean;
  onSelect: (path: string) => void;
}

/** What a value slot is given. Its job is to call `onChange` with the value the operator expects. */
export interface ValueEditorArgs {
  field: FieldSchema | null;
  dataType: string;
  operator: Operator;
  value: ConditionValue;
  /** The arity the operator's wire shape asks for. */
  arity: 'none' | 'one' | 'many' | 'two' | 'relative';
  disabled: boolean;
  onChange: (value: ConditionValue) => void;
}

/** The six types NumberEditor parses. `footage` is numeric to the API and reads as a plain number. */
const NUMERIC_EDITORS = ['number', 'float', 'percent', 'duration', 'timecode', 'currency'] as const;
type NumericEditor = (typeof NUMERIC_EDITORS)[number];

function numericType(dataType: string): NumericEditor {
  return (NUMERIC_EDITORS as readonly string[]).includes(dataType) ? (dataType as NumericEditor) : 'number';
}

function textValue(value: Scalar | undefined): string | null {
  if (value === null || value === undefined) return null;
  return typeof value === 'object' ? null : String(value);
}

function numberValue(value: Scalar | undefined): number | string | null {
  if (value === null || value === undefined || value === '') return null;
  return typeof value === 'number' || typeof value === 'string' ? value : null;
}

function codesOf(value: ConditionValue): string[] {
  if (!Array.isArray(value)) return [];
  return (value as Scalar[]).filter((v): v is string => typeof v === 'string');
}

/** `is` takes one entity hash and `in` a list of them; a list under `is` is a 400 (field_types/entity). */
function entityRefs(value: ConditionValue): EntityRef[] {
  if (Array.isArray(value)) return value.filter((v) => v !== null && typeof v === 'object') as EntityRef[];
  return value !== null && typeof value === 'object' ? [value as EntityRef] : [];
}

function entityRef(value: ConditionValue): EntityRef | null {
  return value !== null && typeof value === 'object' && !Array.isArray(value) ? (value as EntityRef) : null;
}

/** Every dotted path the tree holds. A flat name needs no resolution. */
function dottedPaths(node: FilterNode, out: string[] = []): string[] {
  if (node.kind === 'condition') {
    if (node.path.includes('.')) out.push(node.path);
    return out;
  }
  for (const child of node.conditions) dottedPaths(child, out);
  return out;
}

/** Everything a row needs that does not come from its own node. */
export type FilterEditorSize = 'sm' | 'md' | 'lg';

/** A condition row is a control inside a control, so its ladder sits one step down. */
const BOX: Record<FilterEditorSize, string> = { sm: 'h-7', md: 'h-8', lg: 'h-9' };
const INNER: Record<FilterEditorSize, 'sm' | 'md'> = { sm: 'sm', md: 'sm', lg: 'md' };
const BTN: Record<FilterEditorSize, 'xs' | 'sm' | 'default'> = { sm: 'xs', md: 'sm', lg: 'default' };
const ICON: Record<FilterEditorSize, 'icon-xs' | 'icon-sm' | 'icon'> = {
  sm: 'icon-xs',
  md: 'icon-sm',
  lg: 'icon',
};
const TOGGLE: Record<FilterEditorSize, 'sm' | 'default'> = { sm: 'sm', md: 'sm', lg: 'default' };

interface EditorContext {
  entityType: string;
  context: SgContext;
  hidePaths: string[];
  projectId?: number;
  emptyLabel: string;
  size: FilterEditorSize;
  disabled: boolean;
  fieldChooser?: (args: FieldChooserArgs) => ReactNode;
  valueEditor?: (args: ValueEditorArgs) => ReactNode;
  entityEditor?: (args: ValueEditorArgs) => ReactNode;
  fieldOf: (path: string) => FieldSchema | null;
  /** True while a dotted path is still being walked; its leaf decides the whole row. */
  unresolved: (path: string) => boolean;
  edit: (path: NodePath, node: FilterCondition | FilterGroup) => void;
  remove: (path: NodePath) => void;
  append: (path: NodePath, node: FilterCondition | FilterGroup) => void;
  pickField: (path: NodePath, node: FilterCondition, chosen: string) => void;
  pickPreset: (path: NodePath, node: FilterCondition, id: string) => void;
}

export interface FilterEditorProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange'> {
  /** The root element. */
  ref?: React.Ref<HTMLDivElement>;

  /** Type the root of every field path is read on. */
  entityType: string;
  /** The widget context. Every read goes through it, so widgets on a page share one cache. */
  context: SgContext;
  value: FilterGroup;
  /** Paths to keep out of the field list, each hiding itself and everything under it. */
  hidePaths?: string[];
  /** Scopes the status pickers to the codes one project allows. */
  projectId?: number;
  /** Shown when a group holds no condition. */
  emptyLabel?: string;
  size?: FilterEditorSize;
  disabled?: boolean;
  onChange?: (value: FilterGroup) => void;
  fieldChooser?: (args: FieldChooserArgs) => ReactNode;
  valueEditor?: (args: ValueEditorArgs) => ReactNode;
  entityEditor?: (args: ValueEditorArgs) => ReactNode;
  className?: string;
}

/**
 * A filter tree, edited.
 *
 * A row is a field, an operator and a value; a group nests rows under `All` or
 * `Any`. The operator menu and the value editor both come from the field's
 * `data_type` through core, so a row can only build a filter the API accepts
 * (017_filter_operators). A row with no field, or one whose operator still has no
 * value, is dropped on serialisation rather than sent.
 *
 * The field is chosen with FieldPicker, which descends through links, so a row may
 * filter on a dotted path; the leaf of that path is resolved through the schema
 * service and is what picks the operator menu and the value editor. An operator that
 * pins its value draws no editor at all.
 */
export function FilterEditor({
  entityType,
  context,
  value = emptyFilter(),
  hidePaths = [],
  projectId,
  emptyLabel = NOTHING_CHOSEN_LABEL,
  size = 'md',
  disabled = false,
  onChange,
  fieldChooser,
  valueEditor,
  entityEditor,
  className,
  ref,
  ...rest
}: FilterEditorProps) {
  const fields = useEntityFields(context, entityType);

  /**
   * The leaf schema of every dotted path the tree holds, added once and kept.
   * The in-flight map is a ref, so filling the cache never re-runs the walk.
   */
  const [leaves, setLeaves] = useState<Record<string, FieldSchema | null>>({});
  const resolving = useRef(new Map<string, Promise<FieldSchema | null>>());

  const resolveLeaf = useCallback(
    (path: string): Promise<FieldSchema | null> => {
      const at = `${entityType}|${path}`;
      let job = resolving.current.get(at);
      if (!job) {
        job = context.schema.resolvePath(entityType, path).then(
          (segments) => segments[segments.length - 1]?.field ?? null,
          // A path the schema no longer holds still has to be editable, so the row keeps it.
          () => null,
        );
        resolving.current.set(at, job);
        void job.then((leaf) => {
          setLeaves((held) => ({ ...held, [at]: leaf }));
        });
      }
      return job;
    },
    [context.schema, entityType],
  );

  useEffect(() => {
    for (const path of dottedPaths(value)) void resolveLeaf(path);
  }, [value, resolveLeaf]);

  /** The leaf field of a path. A flat name is a field of the root type. */
  const fieldOf = (path: string): FieldSchema | null => {
    if (!path) return null;
    if (!path.includes('.')) return fields[path] ?? null;
    return leaves[`${entityType}|${path}`] ?? null;
  };

  const dataTypeOf = (path: string): string => fieldOf(path)?.dataType ?? '';
  const commit = (next: FilterGroup) => onChange?.(next);

  const ctx: EditorContext = {
    entityType,
    context,
    hidePaths,
    projectId,
    emptyLabel,
    size,
    disabled,
    fieldChooser,
    valueEditor,
    entityEditor,
    fieldOf,
    unresolved: (path) => path.includes('.') && !(`${entityType}|${path}` in leaves),
    edit: (path, node) => commit(replaceAt(value, path, node)),
    remove: (path) => commit(removeAt(value, path)),
    append: (path, node) => commit(appendAt(value, path, node)),
    pickField: (path, node, chosen) => {
      const before = dataTypeOf(node.path);
      const leaf = chosen.includes('.') ? resolveLeaf(chosen) : Promise.resolve(fields[chosen] ?? null);
      void leaf.then((after) => {
        const type = after?.dataType ?? '';
        // The operator vocabulary is per data type, so moving to another type resets the row.
        commit(
          replaceAt(
            value,
            path,
            before === type && node.path ? { ...node, path: chosen } : defaultCondition(chosen, type),
          ),
        );
      });
    },
    pickPreset: (path, node, id) => {
      const dataType = dataTypeOf(node.path);
      const preset = presetById(dataType, id);
      if (preset) commit(replaceAt(value, path, applyPreset(node, preset, dataType)));
    },
  };

  return (
    <div
      ref={ref}
      data-slot="filter-editor"
      data-entity-type={entityType}
      aria-disabled={disabled ? 'true' : undefined}
      className={cn('flex w-full min-w-0 flex-col gap-3', disabled && 'opacity-50', className)}
      {...rest}
    >
      <GroupNode ctx={ctx} path={[]} node={value} />
    </div>
  );
}

/**
 * A group is a header, its rows and a foot. The header says how the rows join and
 * removes the group; the rows hang off one rail, so a level of nesting is one
 * indent; the foot is where rows and groups are added.
 */
function GroupNode({ ctx, path, node }: { ctx: EditorContext; path: NodePath; node: FilterGroup }) {
  const depth = path.length;
  return (
    <div
      className={cn('flex min-w-0 flex-col gap-2', depth > 0 && 'bg-muted/40 rounded-lg p-2')}
      data-slot="filter-group"
      data-path={path.join('.')}
      data-depth={depth}
      data-logical-operator={node.logicalOperator}
    >
      <div className="flex min-h-9 min-w-0 items-center gap-2" data-slot="filter-group-header">
        <ToggleGroup
          size={TOGGLE[ctx.size]}
          variant="outline"
          disabled={ctx.disabled}
          value={[node.logicalOperator]}
          data-slot="filter-logic"
          onValueChange={(next) => {
            const picked = next[0];
            if (picked) ctx.edit(path, { ...node, logicalOperator: picked as FilterGroup['logicalOperator'] });
          }}
        >
          <ToggleGroupItem value="and" aria-label="Match all">
            All
          </ToggleGroupItem>
          <ToggleGroupItem value="or" aria-label="Match any">
            Any
          </ToggleGroupItem>
        </ToggleGroup>
        <span className="text-muted-foreground min-w-0 flex-1 truncate text-xs">of these match</span>
        {depth > 0 ? (
          <Button
            variant="ghost"
            size={ICON[ctx.size]}
            className="text-muted-foreground hover:text-foreground mt-1 shrink-0 self-start"
            disabled={ctx.disabled}
            aria-label="Remove group"
            data-slot="filter-remove"
            onClick={() => ctx.remove(path)}
          >
            <XIcon />
          </Button>
        ) : null}
      </div>
      <div className="border-border flex min-w-0 flex-col gap-2 border-l pl-3" data-slot="filter-group-body">
        {node.conditions.map((child, i) =>
          child.kind === 'group' ? (
            <GroupNode key={i} ctx={ctx} path={[...path, i]} node={child} />
          ) : (
            <ConditionRow key={i} ctx={ctx} path={[...path, i]} node={child} />
          ),
        )}
        {node.conditions.length === 0 ? (
          <StateLine state="empty" slotName="filter-group-empty" label={ctx.emptyLabel} />
        ) : null}
      </div>
      <div className="flex min-w-0 flex-wrap items-center gap-1 pl-3" data-slot="filter-foot">
        <Button
          variant="ghost"
          size={BTN[ctx.size]}
          className="text-muted-foreground hover:text-foreground"
          disabled={ctx.disabled}
          data-slot="filter-add-condition"
          data-path={path.join('.')}
          onClick={() => ctx.append(path, makeCondition('', 'is', ''))}
        >
          <PlusIcon />
          Condition
        </Button>
        <Button
          variant="ghost"
          size={BTN[ctx.size]}
          className="text-muted-foreground hover:text-foreground"
          disabled={ctx.disabled}
          data-slot="filter-add-group"
          data-path={path.join('.')}
          onClick={() => ctx.append(path, makeGroup('or'))}
        >
          <PlusIcon />
          Group
        </Button>
      </div>
    </div>
  );
}

/**
 * A row is two bands: the field, the operator and the value on one 36px line, and
 * the remove button on its own. The remove sits outside the wrapping band, so it
 * holds the same vertical axis at every depth and never costs the row a line.
 */
function ConditionRow({ ctx, path, node }: { ctx: EditorContext; path: NodePath; node: FilterCondition }) {
  return (
    <div className="flex min-h-9 min-w-0 items-center gap-2" data-slot="filter-row" data-path={path.join('.')}>
      <div className="flex min-w-0 flex-1 flex-wrap items-center gap-2" data-slot="filter-row-content">
        <FieldSlot ctx={ctx} path={path} node={node} />
        <OperatorSlot ctx={ctx} path={path} node={node} />
        <ValueSlot ctx={ctx} path={path} node={node} />
      </div>
      <Button
        variant="ghost"
        size={ICON[ctx.size]}
        className="text-muted-foreground hover:text-foreground mt-1 shrink-0 self-start"
        disabled={ctx.disabled}
        aria-label="Remove condition"
        data-slot="filter-remove"
        onClick={() => ctx.remove(path)}
      >
        <XIcon />
      </Button>
    </div>
  );
}

function FieldSlot({ ctx, path, node }: { ctx: EditorContext; path: NodePath; node: FilterCondition }) {
  return (
    // The field is the row's widest cell: it takes 14rem, truncates, and gives the rest back.
    <div data-slot="filter-field" className="min-w-24 max-w-56 grow basis-24">
      {ctx.fieldChooser ? (
        ctx.fieldChooser({
          entityType: ctx.entityType,
          path: node.path,
          hidePaths: ctx.hidePaths,
          filterableOnly: true,
          disabled: ctx.disabled,
          onSelect: (next: string) => ctx.pickField(path, node, next),
        })
      ) : (
        <FieldPicker
          context={ctx.context}
          entityType={ctx.entityType}
          hidePaths={ctx.hidePaths}
          disabled={ctx.disabled}
          value={node.path}
          deepLinks
          filterableOnly
          clearable={false}
          size={INNER[ctx.size]}
          placeholder="Select a field"
          onValueChange={(next) => ctx.pickField(path, node, next)}
        />
      )}
    </div>
  );
}

function OperatorSlot({ ctx, path, node }: { ctx: EditorContext; path: NodePath; node: FilterCondition }) {
  const dataType = ctx.fieldOf(node.path)?.dataType ?? '';
  const menu = operatorMenu(dataType);
  const current = presetIdOf(node, dataType);
  return (
    <Select
      value={current}
      disabled={ctx.disabled || menu.length === 0}
      onValueChange={(id) => ctx.pickPreset(path, node, id as string)}
    >
      <SelectTrigger className={cn(BOX[ctx.size], 'w-40 shrink-0')} data-slot="filter-operator">
        {presetById(dataType, current)?.label ?? current}
      </SelectTrigger>
      <SelectContent>
        {menu.map((run) => (
          <SelectGroup key={run.label}>
            <SelectLabel>{run.label}</SelectLabel>
            {run.presets.map((preset) => (
              <SelectItem key={preset.id} value={preset.id} data-preset={preset.id}>
                {preset.label}
              </SelectItem>
            ))}
          </SelectGroup>
        ))}
      </SelectContent>
    </Select>
  );
}

function ValueSlot({ ctx, path, node }: { ctx: EditorContext; path: NodePath; node: FilterCondition }) {
  const field = ctx.fieldOf(node.path);
  const dataType = field?.dataType ?? '';
  const kind = valueEditorFor(dataType, node.operator);
  const arity = conditionArity(node, dataType);
  const set = (v: ConditionValue) => ctx.edit(path, { ...node, value: v });
  const disabled = ctx.disabled;
  const args: ValueEditorArgs = { field, dataType, operator: node.operator, value: node.value, arity, disabled, onChange: set };

  return (
    <div className="flex min-w-40 flex-1 flex-wrap items-center gap-2" data-slot="filter-value">
      {ctx.unresolved(node.path) ? (
        <Skeleton className={cn(BOX[ctx.size], 'min-w-0 flex-1')} />
      ) : ctx.valueEditor ? (
        // Integration point: a caller's own editors replace every one below.
        ctx.valueEditor(args)
      ) : arity === 'none' ? (
        // `is empty` and the calendar presets pin their value; there is nothing to edit.
        null
      ) : arity === 'relative' ? (
        <RelativeValue value={node.value} disabled={disabled} size={ctx.size} onChange={set} />
      ) : kind === 'entity' ? (
        ctx.entityEditor ? (
          // Integration point: EntityMultiPicker plugs in here.
          ctx.entityEditor(args)
        ) : (
          <EntityValue ctx={ctx} field={field} value={node.value} arity={arity} onChange={set} />
        )
      ) : kind === 'checkbox' ? (
        <CheckboxEditor
          className="min-w-0 flex-1"
          size={INNER[ctx.size]}
          disabled={disabled}
          field={{ displayName: field?.displayName ?? 'Value', mandatory: false }}
          value={node.value === true}
          onValueChange={(next) => set(next)}
        />
      ) : kind === 'options' && dataType === 'status_list' && arity === 'many' ? (
        <StatusMultiPicker
          className="min-w-0 flex-1"
          size={INNER[ctx.size]}
          context={ctx.context}
          disabled={disabled}
          projectId={ctx.projectId}
          entityType={field?.entityType ?? ctx.entityType}
          field={field?.name}
          value={codesOf(node.value)}
          onValueChange={(next) => set([...next])}
        />
      ) : kind === 'options' && dataType === 'status_list' ? (
        <StatusPicker
          className="min-w-0 flex-1"
          size={INNER[ctx.size]}
          context={ctx.context}
          disabled={disabled}
          projectId={ctx.projectId}
          entityType={field?.entityType ?? ctx.entityType}
          field={field?.name}
          value={typeof node.value === 'string' && node.value !== '' ? node.value : undefined}
          onValueChange={(next) => set(next ?? '')}
        />
      ) : kind === 'options' && arity === 'many' ? (
        <ListMultiPicker
          className="min-w-0 flex-1"
          size={INNER[ctx.size]}
          disabled={disabled}
          field={field}
          placeholder="Select values…"
          value={codesOf(node.value)}
          onValueChange={(next) => set([...next])}
        />
      ) : kind === 'options' ? (
        <ListPicker
          className="min-w-0 flex-1"
          size={INNER[ctx.size]}
          disabled={disabled}
          field={field}
          placeholder="Select a value…"
          value={typeof node.value === 'string' && node.value !== '' ? node.value : null}
          onValueChange={(next) => set(next ?? '')}
        />
      ) : arity === 'two' ? (
        <TwoValues
          kind={kind}
          dataType={dataType}
          value={node.value}
          disabled={disabled}
          size={ctx.size}
          onChange={set}
        />
      ) : arity === 'many' ? (
        <ListValues
          kind={kind}
          dataType={dataType}
          label={field?.displayName ?? 'Value'}
          value={node.value}
          disabled={disabled}
          size={ctx.size}
          onChange={set}
        />
      ) : (
        <ScalarEditor
          kind={kind}
          dataType={dataType}
          label={field?.displayName ?? 'Value'}
          value={node.value as Scalar}
          disabled={disabled}
          size={ctx.size}
          onChange={(v) => set(v)}
        />
      )}
    </div>
  );
}

/**
 * A value editor sized for a row. The typed types take the width their content needs and
 * the free width goes to the ones that hold a name: a date, a time and a number never
 * push the row onto a second line.
 */
function ScalarEditor({
  kind,
  dataType,
  label,
  value,
  disabled,
  size,
  onChange,
}: {
  kind: string;
  dataType: string;
  label: string;
  value: Scalar;
  disabled: boolean;
  size: FilterEditorSize;
  onChange: (v: Scalar) => void;
}) {
  const field = { displayName: label, mandatory: false };
  if (kind === 'number') {
    return (
      <NumberEditor
        className="shrink-0"
        size={INNER[size]}
        inline
        disabled={disabled}
        dataType={numericType(dataType)}
        field={field}
        value={numberValue(value)}
        onValueChange={(next) => onChange(next ?? '')}
      />
    );
  }
  if (kind === 'date') {
    return (
      <DateEditor
        className="shrink-0"
        size={INNER[size]}
        inline
        disabled={disabled}
        field={field}
        value={textValue(value)}
        onValueChange={(next) => onChange(next ?? '')}
      />
    );
  }
  if (kind === 'date_time') {
    return (
      <DateTimeEditor
        className="shrink-0"
        size={INNER[size]}
        inline
        hint={false}
        disabled={disabled}
        field={field}
        value={textValue(value)}
        onValueChange={(next) => onChange(next ?? '')}
      />
    );
  }
  if (kind === 'color') {
    return (
      <ColorEditor
        className="w-44 shrink-0"
        size={INNER[size]}
        hint={false}
        disabled={disabled}
        field={field}
        value={textValue(value)}
        onValueChange={(next) => onChange(next ?? '')}
      />
    );
  }
  if (kind === 'url') {
    const href = textValue(value);
    return (
      // The row compares the link itself, so the editor's name half is left out of the value.
      <UrlEditor
        className="min-w-0 flex-1"
        size={INNER[size]}
        disabled={disabled}
        field={field}
        value={href ? { url: String(href) } : null}
        onValueChange={(next) => onChange(next?.url ?? '')}
      />
    );
  }
  return (
    <TextEditor
      className="min-w-0 flex-1"
      size={INNER[size]}
      disabled={disabled}
      field={field}
      value={textValue(value)}
      onValueChange={(next) => onChange(next ?? '')}
    />
  );
}

/**
 * A list of values, one to a line, each edited by its own data type's control and each
 * with the control that drops it. The arity is the operator's: `in` and `not_in` take a
 * JSON array, and a blank value is dropped on serialisation rather than sent.
 */
function ListValues({
  kind,
  dataType,
  label,
  value,
  disabled,
  size,
  onChange,
}: {
  kind: string;
  dataType: string;
  label: string;
  value: ConditionValue;
  disabled: boolean;
  size: FilterEditorSize;
  onChange: (v: ConditionValue) => void;
}) {
  const items = conditionList(value);
  return (
    <div className="flex min-w-0 flex-1 flex-col items-start gap-2" data-slot="filter-list">
      {items.map((item, i) => (
        <div className="flex min-w-0 items-center gap-1.5" data-slot="filter-list-value" data-index={i} key={i}>
          <ScalarEditor
            kind={kind}
            dataType={dataType}
            label={label}
            value={item}
            disabled={disabled}
            size={size}
            onChange={(v) => onChange(withListValue(value, i, v) as ConditionValue)}
          />
          <Button
            variant="ghost"
            size={ICON[size]}
            className="text-muted-foreground hover:text-foreground shrink-0"
            disabled={disabled}
            aria-label="Remove value"
            data-slot="filter-list-remove"
            onClick={() => onChange(withoutListValue(value, i) as ConditionValue)}
          >
            <XIcon />
          </Button>
        </div>
      ))}
      <Button
        variant="ghost"
        size={BTN[size]}
        className="text-muted-foreground hover:text-foreground shrink-0"
        disabled={disabled}
        data-slot="filter-list-add"
        onClick={() => onChange(withAddedListValue(value) as ConditionValue)}
      >
        <PlusIcon />
        Value
      </Button>
    </div>
  );
}

function RelativeValue({
  value,
  disabled,
  size,
  onChange,
}: {
  value: ConditionValue;
  disabled: boolean;
  size: FilterEditorSize;
  onChange: (v: ConditionValue) => void;
}) {
  const window_ = relativeWindow(value);
  return (
    // A window is a count and a unit: the number editor and the list a `list` field uses.
    <div className="flex min-w-0 shrink-0 items-center gap-2" data-slot="filter-window">
      <NumberEditor
        className="w-16 shrink-0"
        size={INNER[size]}
        inline
        disabled={disabled}
        dataType="number"
        min={1}
        field={{ displayName: 'Count', mandatory: true }}
        value={window_.count}
        onValueChange={(next) =>
          onChange(withRelativeWindow(value, { count: next === null ? null : Number(next) }) as ConditionValue)
        }
      />
      <ListPicker
        className="w-24 shrink-0"
        size={INNER[size]}
        disabled={disabled}
        field={timeUnitField()}
        value={window_.unit}
        onValueChange={(next) => onChange(withRelativeWindow(value, { unit: (next ?? 'DAY') as TimeUnit }) as ConditionValue)}
      />
    </div>
  );
}

function TwoValues({
  kind,
  dataType,
  value,
  disabled,
  size,
  onChange,
}: {
  kind: string;
  dataType: string;
  value: ConditionValue;
  disabled: boolean;
  size: FilterEditorSize;
  onChange: (v: ConditionValue) => void;
}) {
  const pair = (Array.isArray(value) ? value : [null, null]) as [Scalar, Scalar];
  return (
    // Both ends on one line, joined by the word that reads the range.
    <div className="flex min-w-0 flex-1 flex-wrap items-center gap-2" data-slot="filter-range">
      <ScalarEditor
        kind={kind}
        dataType={dataType}
        label="From"
        value={pair[0]}
        disabled={disabled}
        size={size}
        onChange={(v) => onChange([v, pair[1]] as ConditionValue)}
      />
      <span className="text-muted-foreground shrink-0 text-sm">and</span>
      <ScalarEditor
        kind={kind}
        dataType={dataType}
        label="To"
        value={pair[1]}
        disabled={disabled}
        size={size}
        onChange={(v) => onChange([pair[0], v] as ConditionValue)}
      />
    </div>
  );
}

function EntityValue({
  ctx,
  field,
  value,
  arity,
  onChange,
}: {
  ctx: EditorContext;
  field: FieldSchema | null;
  value: ConditionValue;
  arity: string;
  onChange: (v: ConditionValue) => void;
}) {
  const types = field?.validTypes?.length ? field.validTypes : [ctx.entityType];
  if (arity === 'many') {
    return (
      <EntityMultiPicker
        className="min-w-0 flex-1"
        size={INNER[ctx.size]}
        context={ctx.context}
        disabled={ctx.disabled}
        projectId={ctx.projectId}
        entityTypes={types}
        placeholder="Search entities"
        value={entityRefs(value)}
        onValueChange={(next) => onChange([...next])}
      />
    );
  }
  return (
    <EntityPicker
      className="min-w-0 flex-1"
      size={INNER[ctx.size]}
      context={ctx.context}
      disabled={ctx.disabled}
      projectId={ctx.projectId}
      entityTypes={types}
      placeholder="Search entities"
      value={entityRef(value)}
      onValueChange={(next) => onChange(next ?? '')}
    />
  );
}
