// packages/svelte/src/lib/registry/components/match-text.svelte
<script lang="ts">
	import type { HTMLAttributes } from 'svelte/elements';
	import { matchRuns } from 'sg-widgets-core';
	import { cn, type WithElementRef } from '$lib/utils.js';

	type Props = WithElementRef<Omit<HTMLAttributes<HTMLSpanElement>, 'children'>, HTMLSpanElement> & {
		/** The label to draw. */
		text: string;
		/** What was searched for. Its whitespace-separated words are the ones marked. */
		query?: string;
	};

	let { text, query = '', class: className, ref = $bindable(null), ...rest }: Props = $props();
</script>

<!--
	A label with the query's matched runs at the weight `docs/design-rules.md` rule 6
	gives them.

	`POST /entity/_text_search` matches a row when every word of the query appears in
	it, so every word is marked wherever it occurs and overlapping words merge into one
	run (053_text_search_matching). Emphasis is weight and never colour, so a row that
	carries its own colour still reads. The runs are text: nothing here sets HTML from
	a row, and they rebuild the label exactly, so a label with no match draws as itself.
-->
<span data-slot="match-text" bind:this={ref} class={cn(className)} {...rest}
	>{#each matchRuns(text, query) as run, i (i)}<span
			class={run.match ? 'font-semibold' : undefined}>{run.text}</span
		>{/each}</span
>

// packages/react/src/registry/sg/components/match-text.tsx
import type * as React from 'react';
import { matchRuns } from '@sg-widgets/core';
import { cn } from '@/lib/utils';

export interface MatchTextProps extends Omit<React.HTMLAttributes<HTMLSpanElement>, 'children'> {
  /** The root element. */
  ref?: React.Ref<HTMLSpanElement>;

  /** The label to draw. */
  text: string;
  /** What was searched for. Its whitespace-separated words are the ones marked. */
  query?: string;
}

/**
 * A label with the query's matched runs at the weight `docs/design-rules.md` rule 6
 * gives them.
 *
 * `POST /entity/_text_search` matches a row when every word of the query appears in
 * it, so every word is marked wherever it occurs and overlapping words merge into one
 * run (053_text_search_matching). Emphasis is weight and never colour, so a row that
 * carries its own colour still reads. The runs are text: nothing here sets HTML from
 * a row, and they rebuild the label exactly, so a label with no match draws as itself.
 */
export function MatchText({ text, query = '', className, ref, ...rest }: MatchTextProps) {
  return (
    <span data-slot="match-text" ref={ref} className={cn(className)} {...rest}>
      {matchRuns(text, query).map((run, i) => (
        <span key={i} className={run.match ? 'font-semibold' : undefined}>
          {run.text}
        </span>
      ))}
    </span>
  );
}
